/*******************************************************************************
 * Copyright (c) 2003, 2007 IBM Corporation Licensed Material - Property of IBM. All rights reserved.
 *  
 * US Government Users Restricted Rights - Use, duplication or disclosure v1.0 restricted by GSA ADP
 * Schedule Contract with IBM Corp.
 * 
 * Contributors: IBM Corporation - initial API and implementation
 *******************************************************************************/
package com.ibm.ccl.soa.deploy.j2ee.validation;

import java.math.BigInteger;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.j2ee.J2EEDatasource}. This
 * doesn't really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface J2EEDatasourceValidator {
	boolean validate();

	boolean validateDatasourceName(String value);

	boolean validateDbName(String value);

	boolean validateHostname(String value);

	boolean validateJndiName(String value);

	boolean validatePassword(String value);

	boolean validatePort(BigInteger value);

	boolean validateUsedForCmp(boolean value);

	boolean validateUsername(String value);
}
