/*******************************************************************************
 * Copyright (c) 2003, 2007 IBM Corporation Licensed Material - Property of IBM. All rights reserved.
 *  
 * US Government Users Restricted Rights - Use, duplication or disclosure v1.0 restricted by GSA ADP
 * Schedule Contract with IBM Corp.
 * 
 * Contributors: IBM Corporation - initial API and implementation
 *******************************************************************************/
package com.ibm.ccl.soa.deploy.ihs.validation;

import org.eclipse.emf.common.util.EMap;
import org.eclipse.emf.ecore.util.FeatureMap;

import com.ibm.ccl.soa.deploy.ihs.IhsModule;
import com.ibm.ccl.soa.deploy.ihs.IhsServer;
import com.ibm.ccl.soa.deploy.ihs.IhsServerUnit;
import com.ibm.ccl.soa.deploy.ihs.IhsSystem;
import com.ibm.ccl.soa.deploy.ihs.IhsSystemUnit;
import com.ibm.ccl.soa.deploy.ihs.IhsUser;
import com.ibm.ccl.soa.deploy.ihs.IhsUserRepository;
import com.ibm.ccl.soa.deploy.ihs.IhsUserUnit;
import com.ibm.ccl.soa.deploy.ihs.IhsWasAdminModule;
import com.ibm.ccl.soa.deploy.ihs.IhsWasAdminModuleUnit;
import com.ibm.ccl.soa.deploy.ihs.IhsWasModule;
import com.ibm.ccl.soa.deploy.ihs.IhsWasModuleUnit;
import com.ibm.ccl.soa.deploy.ihs.LinuxIhsSystem;
import com.ibm.ccl.soa.deploy.ihs.WindowsIhsSystem;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.ihs.IHSDeployRoot}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IHSDeployRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);

	boolean validateXMLNSPrefixMap(EMap value);

	boolean validateXSISchemaLocation(EMap value);

	boolean validateCapabilityIhsModule(IhsModule value);

	boolean validateCapabilityIhsServer(IhsServer value);

	boolean validateCapabilityIhsSystem(IhsSystem value);

	boolean validateCapabilityIhsUser(IhsUser value);

	boolean validateCapabilityIhsUserRepository(IhsUserRepository value);

	boolean validateCapabilityIhsWasAdminModule(IhsWasAdminModule value);

	boolean validateCapabilityIhsWasModule(IhsWasModule value);

	boolean validateCapabilityLinuxIhsSystem(LinuxIhsSystem value);

	boolean validateCapabilityWindowsIhsSystem(WindowsIhsSystem value);

	boolean validateUnitIhsServerUnit(IhsServerUnit value);

	boolean validateUnitIhsSystemUnit(IhsSystemUnit value);

	boolean validateUnitIhsUserUnit(IhsUserUnit value);

	boolean validateUnitIhsWasAdminModuleUnit(IhsWasAdminModuleUnit value);

	boolean validateUnitIhsWasModuleUnit(IhsWasModuleUnit value);
}
