/*******************************************************************************
 * Copyright (c) 2003, 2007 IBM Corporation Licensed Material - Property of IBM. All rights reserved.
 *  
 * US Government Users Restricted Rights - Use, duplication or disclosure v1.0 restricted by GSA ADP
 * Schedule Contract with IBM Corp.
 * 
 * Contributors: IBM Corporation - initial API and implementation
 *******************************************************************************/
package com.ibm.ccl.soa.deploy.was.validation;

import java.math.BigInteger;

import com.ibm.ccl.soa.deploy.was.WasApplicationMap;
import com.ibm.ccl.soa.deploy.was.WasWebServerOS;
import com.ibm.ccl.soa.deploy.was.WasWebServerType;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.was.WasWebServer}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WasWebServerValidator {
	boolean validate();

	boolean validateConfigFile(String value);

	boolean validateHost(String value);

	boolean validateInstallLocation(String value);

	boolean validateLogFileAccess(String value);

	boolean validateLogFileError(String value);

	boolean validateMapApplications(WasApplicationMap value);

	boolean validateOperatingSystem(WasWebServerOS value);

	boolean validatePort(BigInteger value);

	boolean validateServerName(String value);

	boolean validateServiceName(String value);

	boolean validateType(WasWebServerType value);

	boolean validateUseSecureProtocol(boolean value);
}
