/*******************************************************************************
 * Copyright (c) 2003, 2007 IBM Corporation Licensed Material - Property of IBM. All rights reserved.
 *  
 * US Government Users Restricted Rights - Use, duplication or disclosure v1.0 restricted by GSA ADP
 * Schedule Contract with IBM Corp.
 * 
 * Contributors: IBM Corporation - initial API and implementation
 *******************************************************************************/
package com.ibm.ccl.soa.deploy.db2.validation;

import org.eclipse.emf.common.util.EMap;
import org.eclipse.emf.ecore.util.FeatureMap;

import com.ibm.ccl.soa.deploy.db2.DB2AdminClient;
import com.ibm.ccl.soa.deploy.db2.DB2AdminClientUnit;
import com.ibm.ccl.soa.deploy.db2.DB2AdminServer;
import com.ibm.ccl.soa.deploy.db2.DB2AdminServerUnit;
import com.ibm.ccl.soa.deploy.db2.DB2AppDevelClient;
import com.ibm.ccl.soa.deploy.db2.DB2AppDevelClientUnit;
import com.ibm.ccl.soa.deploy.db2.DB2BaseClientUnit;
import com.ibm.ccl.soa.deploy.db2.DB2BaseInstance;
import com.ibm.ccl.soa.deploy.db2.DB2CatalogUnit;
import com.ibm.ccl.soa.deploy.db2.DB2CatalogedNode;
import com.ibm.ccl.soa.deploy.db2.DB2Client;
import com.ibm.ccl.soa.deploy.db2.DB2ClientInstance;
import com.ibm.ccl.soa.deploy.db2.DB2ClientInstanceUnit;
import com.ibm.ccl.soa.deploy.db2.DB2DDLArtifact;
import com.ibm.ccl.soa.deploy.db2.DB2Database;
import com.ibm.ccl.soa.deploy.db2.DB2DatabaseUnit;
import com.ibm.ccl.soa.deploy.db2.DB2Instance;
import com.ibm.ccl.soa.deploy.db2.DB2InstanceUnit;
import com.ibm.ccl.soa.deploy.db2.DB2JdbcDriver;
import com.ibm.ccl.soa.deploy.db2.DB2NodeCatalogUnit;
import com.ibm.ccl.soa.deploy.db2.DB2RuntimeClientUnit;
import com.ibm.ccl.soa.deploy.db2.DB2System;
import com.ibm.ccl.soa.deploy.db2.DB2SystemUnit;
import com.ibm.ccl.soa.deploy.db2.UnixDB2AdminServer;
import com.ibm.ccl.soa.deploy.db2.UnixDB2ClientInstance;
import com.ibm.ccl.soa.deploy.db2.UnixDB2Instance;
import com.ibm.ccl.soa.deploy.db2.UnixDB2System;
import com.ibm.ccl.soa.deploy.db2.WindowsDB2AdminServer;
import com.ibm.ccl.soa.deploy.db2.WindowsDB2ClientInstance;
import com.ibm.ccl.soa.deploy.db2.WindowsDB2Instance;
import com.ibm.ccl.soa.deploy.db2.WindowsDB2System;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.db2.Db2DeployRoot}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Db2DeployRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);

	boolean validateXMLNSPrefixMap(EMap value);

	boolean validateXSISchemaLocation(EMap value);

	boolean validateCapabilityDb2AdminClient(DB2AdminClient value);

	boolean validateCapabilityDb2AdminServer(DB2AdminServer value);

	boolean validateCapabilityDb2AppDevelClient(DB2AppDevelClient value);

	boolean validateCapabilityDb2BaseInstance(DB2BaseInstance value);

	boolean validateCapabilityDb2CatalogedNode(DB2CatalogedNode value);

	boolean validateCapabilityDb2Client(DB2Client value);

	boolean validateCapabilityDb2ClientInstance(DB2ClientInstance value);

	boolean validateCapabilityDb2Database(DB2Database value);

	boolean validateCapabilityDb2Instance(DB2Instance value);

	boolean validateCapabilityDb2JdbcDriver(DB2JdbcDriver value);

	boolean validateCapabilityDb2System(DB2System value);

	boolean validateCapabilityUnixDb2AdminServer(UnixDB2AdminServer value);

	boolean validateCapabilityUnixDb2ClientInstance(UnixDB2ClientInstance value);

	boolean validateCapabilityUnixDb2Instance(UnixDB2Instance value);

	boolean validateCapabilityUnixDb2System(UnixDB2System value);

	boolean validateCapabilityWindowsDb2AdminServer(WindowsDB2AdminServer value);

	boolean validateCapabilityWindowsDb2ClientInstance(WindowsDB2ClientInstance value);

	boolean validateCapabilityWindowsDb2Instance(WindowsDB2Instance value);

	boolean validateCapabilityWindowsDb2System(WindowsDB2System value);

	boolean validateUnitDb2AdminClientUnit(DB2AdminClientUnit value);

	boolean validateUnitDb2AdminServerUnit(DB2AdminServerUnit value);

	boolean validateUnitDb2AppDevelClientUnit(DB2AppDevelClientUnit value);

	boolean validateUnitDb2BaseClientUnit(DB2BaseClientUnit value);

	boolean validateUnitDb2CatalogUnit(DB2CatalogUnit value);

	boolean validateUnitDb2ClientInstanceUnit(DB2ClientInstanceUnit value);

	boolean validateUnitDb2DatabaseUnit(DB2DatabaseUnit value);

	boolean validateUnitDb2ddl(DB2DDLArtifact value);

	boolean validateUnitDb2InstanceUnit(DB2InstanceUnit value);

	boolean validateUnitDb2NodeCatalogUnit(DB2NodeCatalogUnit value);

	boolean validateUnitDb2RuntimeClientUnit(DB2RuntimeClientUnit value);

	boolean validateUnitDb2SystemUnit(DB2SystemUnit value);
}
