/*******************************************************************************
 * Copyright (c) 2003, 2007 IBM Corporation Licensed Material - Property of IBM. All rights reserved.
 *  
 * US Government Users Restricted Rights - Use, duplication or disclosure v1.0 restricted by GSA ADP
 * Schedule Contract with IBM Corp.
 * 
 * Contributors: IBM Corporation - initial API and implementation
 *******************************************************************************/
package com.ibm.ccl.soa.deploy.db2.validation;

import java.math.BigInteger;

import com.ibm.ccl.soa.deploy.db2.PageSizeType;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.db2.DB2Database}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DB2DatabaseValidator {
	boolean validate();

	boolean validateCatalogSp(String value);

	boolean validateCodeSet(String value);

	boolean validateCreatePath(String value);

	boolean validateDb2Version(String value);

	boolean validateDbAlias(String value);

	boolean validateDbDrive(String value);

	boolean validateDbName(String value);

	boolean validateDftExtentSize(BigInteger value);

	boolean validatePageSize(PageSizeType value);

	boolean validateTempSp(String value);

	boolean validateTerritory(String value);

	boolean validateUserSp(String value);
}
