/*******************************************************************************
 * Copyright (c) 2003, 2007 IBM Corporation Licensed Material - Property of IBM. All rights reserved.
 *  
 * US Government Users Restricted Rights - Use, duplication or disclosure v1.0 restricted by GSA ADP
 * Schedule Contract with IBM Corp.
 * 
 * Contributors: IBM Corporation - initial API and implementation
 *******************************************************************************/
package com.ibm.ccl.soa.deploy.was.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import com.ibm.ccl.soa.deploy.was.util.WasAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc --> <!--
 * end-user-doc -->
 * @generated
 */
public class WasItemProviderAdapterFactory extends WasAdapterFactory implements
		ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public static final String copyright = "Copyright (c) 2005, 2006 IBM Corporation. Licensed Material - Property of IBM. All rights reserved."; //$NON-NLS-1$

	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection supportedTypes = new ArrayList();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public WasItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.Classloader} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected ClassloaderItemProvider classloaderItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.Classloader}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createClassloaderAdapter() {
		if (classloaderItemProvider == null) {
			classloaderItemProvider = new ClassloaderItemProvider(this);
		}

		return classloaderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.DB2JdbcProvider} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected DB2JdbcProviderItemProvider db2JdbcProviderItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.DB2JdbcProvider}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createDB2JdbcProviderAdapter() {
		if (db2JdbcProviderItemProvider == null) {
			db2JdbcProviderItemProvider = new DB2JdbcProviderItemProvider(this);
		}

		return db2JdbcProviderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.DB2JdbcProviderUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected DB2JdbcProviderUnitItemProvider db2JdbcProviderUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.DB2JdbcProviderUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createDB2JdbcProviderUnitAdapter() {
		if (db2JdbcProviderUnitItemProvider == null) {
			db2JdbcProviderUnitItemProvider = new DB2JdbcProviderUnitItemProvider(this);
		}

		return db2JdbcProviderUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.DerbyJdbcProvider} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected DerbyJdbcProviderItemProvider derbyJdbcProviderItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.DerbyJdbcProvider}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createDerbyJdbcProviderAdapter() {
		if (derbyJdbcProviderItemProvider == null) {
			derbyJdbcProviderItemProvider = new DerbyJdbcProviderItemProvider(this);
		}

		return derbyJdbcProviderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.DerbyJdbcProviderUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DerbyJdbcProviderUnitItemProvider derbyJdbcProviderUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.DerbyJdbcProviderUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createDerbyJdbcProviderUnitAdapter() {
		if (derbyJdbcProviderUnitItemProvider == null) {
			derbyJdbcProviderUnitItemProvider = new DerbyJdbcProviderUnitItemProvider(this);
		}

		return derbyJdbcProviderUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.ExtendedJdbcProvider} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtendedJdbcProviderItemProvider extendedJdbcProviderItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.ExtendedJdbcProvider}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createExtendedJdbcProviderAdapter() {
		if (extendedJdbcProviderItemProvider == null) {
			extendedJdbcProviderItemProvider = new ExtendedJdbcProviderItemProvider(this);
		}

		return extendedJdbcProviderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.ExtendedJdbcProviderUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtendedJdbcProviderUnitItemProvider extendedJdbcProviderUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.ExtendedJdbcProviderUnit}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExtendedJdbcProviderUnitAdapter() {
		if (extendedJdbcProviderUnitItemProvider == null) {
			extendedJdbcProviderUnitItemProvider = new ExtendedJdbcProviderUnitItemProvider(this);
		}

		return extendedJdbcProviderUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.HostNameAliasType} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected HostNameAliasTypeItemProvider hostNameAliasTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.HostNameAliasType}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createHostNameAliasTypeAdapter() {
		if (hostNameAliasTypeItemProvider == null) {
			hostNameAliasTypeItemProvider = new HostNameAliasTypeItemProvider(this);
		}

		return hostNameAliasTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.SharedLibraryEntry} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected SharedLibraryEntryItemProvider sharedLibraryEntryItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.SharedLibraryEntry}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createSharedLibraryEntryAdapter() {
		if (sharedLibraryEntryItemProvider == null) {
			sharedLibraryEntryItemProvider = new SharedLibraryEntryItemProvider(this);
		}

		return sharedLibraryEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.VirtualHostType} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected VirtualHostTypeItemProvider virtualHostTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.VirtualHostType}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createVirtualHostTypeAdapter() {
		if (virtualHostTypeItemProvider == null) {
			virtualHostTypeItemProvider = new VirtualHostTypeItemProvider(this);
		}

		return virtualHostTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasAdvancedLdapConfiguration} instances.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasAdvancedLdapConfigurationItemProvider wasAdvancedLdapConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasAdvancedLdapConfiguration}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasAdvancedLdapConfigurationAdapter() {
		if (wasAdvancedLdapConfigurationItemProvider == null) {
			wasAdvancedLdapConfigurationItemProvider = new WasAdvancedLdapConfigurationItemProvider(this);
		}

		return wasAdvancedLdapConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WasApplicationClassLoaderPolicy} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WasApplicationClassLoaderPolicyItemProvider wasApplicationClassLoaderPolicyItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasApplicationClassLoaderPolicy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasApplicationClassLoaderPolicyAdapter() {
		if (wasApplicationClassLoaderPolicyItemProvider == null) {
			wasApplicationClassLoaderPolicyItemProvider = new WasApplicationClassLoaderPolicyItemProvider(this);
		}

		return wasApplicationClassLoaderPolicyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasApplicationExt} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasApplicationExtItemProvider wasApplicationExtItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasApplicationExt}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasApplicationExtAdapter() {
		if (wasApplicationExtItemProvider == null) {
			wasApplicationExtItemProvider = new WasApplicationExtItemProvider(this);
		}

		return wasApplicationExtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WasApplicationServerClassLoaderPolicy} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WasApplicationServerClassLoaderPolicyItemProvider wasApplicationServerClassLoaderPolicyItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasApplicationServerClassLoaderPolicy}.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasApplicationServerClassLoaderPolicyAdapter() {
		if (wasApplicationServerClassLoaderPolicyItemProvider == null) {
			wasApplicationServerClassLoaderPolicyItemProvider = new WasApplicationServerClassLoaderPolicyItemProvider(this);
		}

		return wasApplicationServerClassLoaderPolicyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasCell} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasCellItemProvider wasCellItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasCell}.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasCellAdapter() {
		if (wasCellItemProvider == null) {
			wasCellItemProvider = new WasCellItemProvider(this);
		}

		return wasCellItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasCellUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasCellUnitItemProvider wasCellUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasCellUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasCellUnitAdapter() {
		if (wasCellUnitItemProvider == null) {
			wasCellUnitItemProvider = new WasCellUnitItemProvider(this);
		}

		return wasCellUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WasClassLoaderConfigurationUnit} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WasClassLoaderConfigurationUnitItemProvider wasClassLoaderConfigurationUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasClassLoaderConfigurationUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasClassLoaderConfigurationUnitAdapter() {
		if (wasClassLoaderConfigurationUnitItemProvider == null) {
			wasClassLoaderConfigurationUnitItemProvider = new WasClassLoaderConfigurationUnitItemProvider(this);
		}

		return wasClassLoaderConfigurationUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasClassLoaderPolicy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasClassLoaderPolicyItemProvider wasClassLoaderPolicyItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasClassLoaderPolicy}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasClassLoaderPolicyAdapter() {
		if (wasClassLoaderPolicyItemProvider == null) {
			wasClassLoaderPolicyItemProvider = new WasClassLoaderPolicyItemProvider(this);
		}

		return wasClassLoaderPolicyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasCluster} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasClusterItemProvider wasClusterItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasCluster}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasClusterAdapter() {
		if (wasClusterItemProvider == null) {
			wasClusterItemProvider = new WasClusterItemProvider(this);
		}

		return wasClusterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasClusterUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasClusterUnitItemProvider wasClusterUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasClusterUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasClusterUnitAdapter() {
		if (wasClusterUnitItemProvider == null) {
			wasClusterUnitItemProvider = new WasClusterUnitItemProvider(this);
		}

		return wasClusterUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasConfigurationContainer} instances.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasConfigurationContainerItemProvider wasConfigurationContainerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasConfigurationContainer}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasConfigurationContainerAdapter() {
		if (wasConfigurationContainerItemProvider == null) {
			wasConfigurationContainerItemProvider = new WasConfigurationContainerItemProvider(this);
		}

		return wasConfigurationContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasDatasource} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasDatasourceItemProvider wasDatasourceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasDatasource}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasDatasourceAdapter() {
		if (wasDatasourceItemProvider == null) {
			wasDatasourceItemProvider = new WasDatasourceItemProvider(this);
		}

		return wasDatasourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasDatasourceUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasDatasourceUnitItemProvider wasDatasourceUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasDatasourceUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasDatasourceUnitAdapter() {
		if (wasDatasourceUnitItemProvider == null) {
			wasDatasourceUnitItemProvider = new WasDatasourceUnitItemProvider(this);
		}

		return wasDatasourceUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingConnectionFactoryConfiguration} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasDefaultMessagingConnectionFactoryConfigurationItemProvider wasDefaultMessagingConnectionFactoryConfigurationItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingConnectionFactoryConfiguration}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasDefaultMessagingConnectionFactoryConfigurationAdapter() {
		if (wasDefaultMessagingConnectionFactoryConfigurationItemProvider == null) {
			wasDefaultMessagingConnectionFactoryConfigurationItemProvider = new WasDefaultMessagingConnectionFactoryConfigurationItemProvider(this);
		}

		return wasDefaultMessagingConnectionFactoryConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingConnectionFactoryUnit} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WasDefaultMessagingConnectionFactoryUnitItemProvider wasDefaultMessagingConnectionFactoryUnitItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingConnectionFactoryUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasDefaultMessagingConnectionFactoryUnitAdapter() {
		if (wasDefaultMessagingConnectionFactoryUnitItemProvider == null) {
			wasDefaultMessagingConnectionFactoryUnitItemProvider = new WasDefaultMessagingConnectionFactoryUnitItemProvider(this);
		}

		return wasDefaultMessagingConnectionFactoryUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingQueueConnectionFactoryConfiguration} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasDefaultMessagingQueueConnectionFactoryConfigurationItemProvider wasDefaultMessagingQueueConnectionFactoryConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingQueueConnectionFactoryConfiguration}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasDefaultMessagingQueueConnectionFactoryConfigurationAdapter() {
		if (wasDefaultMessagingQueueConnectionFactoryConfigurationItemProvider == null) {
			wasDefaultMessagingQueueConnectionFactoryConfigurationItemProvider = new WasDefaultMessagingQueueConnectionFactoryConfigurationItemProvider(this);
		}

		return wasDefaultMessagingQueueConnectionFactoryConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingQueueConnectionFactoryUnit} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasDefaultMessagingQueueConnectionFactoryUnitItemProvider wasDefaultMessagingQueueConnectionFactoryUnitItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingQueueConnectionFactoryUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasDefaultMessagingQueueConnectionFactoryUnitAdapter() {
		if (wasDefaultMessagingQueueConnectionFactoryUnitItemProvider == null) {
			wasDefaultMessagingQueueConnectionFactoryUnitItemProvider = new WasDefaultMessagingQueueConnectionFactoryUnitItemProvider(this);
		}

		return wasDefaultMessagingQueueConnectionFactoryUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingQueueDestination} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WasDefaultMessagingQueueDestinationItemProvider wasDefaultMessagingQueueDestinationItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingQueueDestination}.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasDefaultMessagingQueueDestinationAdapter() {
		if (wasDefaultMessagingQueueDestinationItemProvider == null) {
			wasDefaultMessagingQueueDestinationItemProvider = new WasDefaultMessagingQueueDestinationItemProvider(this);
		}

		return wasDefaultMessagingQueueDestinationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingQueueDestinationUnit} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WasDefaultMessagingQueueDestinationUnitItemProvider wasDefaultMessagingQueueDestinationUnitItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingQueueDestinationUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasDefaultMessagingQueueDestinationUnitAdapter() {
		if (wasDefaultMessagingQueueDestinationUnitItemProvider == null) {
			wasDefaultMessagingQueueDestinationUnitItemProvider = new WasDefaultMessagingQueueDestinationUnitItemProvider(this);
		}

		return wasDefaultMessagingQueueDestinationUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingTopicConnectionFactoryConfiguration} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasDefaultMessagingTopicConnectionFactoryConfigurationItemProvider wasDefaultMessagingTopicConnectionFactoryConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingTopicConnectionFactoryConfiguration}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasDefaultMessagingTopicConnectionFactoryConfigurationAdapter() {
		if (wasDefaultMessagingTopicConnectionFactoryConfigurationItemProvider == null) {
			wasDefaultMessagingTopicConnectionFactoryConfigurationItemProvider = new WasDefaultMessagingTopicConnectionFactoryConfigurationItemProvider(this);
		}

		return wasDefaultMessagingTopicConnectionFactoryConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingTopicConnectionFactoryUnit} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasDefaultMessagingTopicConnectionFactoryUnitItemProvider wasDefaultMessagingTopicConnectionFactoryUnitItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingTopicConnectionFactoryUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasDefaultMessagingTopicConnectionFactoryUnitAdapter() {
		if (wasDefaultMessagingTopicConnectionFactoryUnitItemProvider == null) {
			wasDefaultMessagingTopicConnectionFactoryUnitItemProvider = new WasDefaultMessagingTopicConnectionFactoryUnitItemProvider(this);
		}

		return wasDefaultMessagingTopicConnectionFactoryUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingTopicDestination} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WasDefaultMessagingTopicDestinationItemProvider wasDefaultMessagingTopicDestinationItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingTopicDestination}.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasDefaultMessagingTopicDestinationAdapter() {
		if (wasDefaultMessagingTopicDestinationItemProvider == null) {
			wasDefaultMessagingTopicDestinationItemProvider = new WasDefaultMessagingTopicDestinationItemProvider(this);
		}

		return wasDefaultMessagingTopicDestinationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingTopicDestinationUnit} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WasDefaultMessagingTopicDestinationUnitItemProvider wasDefaultMessagingTopicDestinationUnitItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link com.ibm.ccl.soa.deploy.was.WasDefaultMessagingTopicDestinationUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasDefaultMessagingTopicDestinationUnitAdapter() {
		if (wasDefaultMessagingTopicDestinationUnitItemProvider == null) {
			wasDefaultMessagingTopicDestinationUnitItemProvider = new WasDefaultMessagingTopicDestinationUnitItemProvider(this);
		}

		return wasDefaultMessagingTopicDestinationUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasDeploymentManager} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasDeploymentManagerItemProvider wasDeploymentManagerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasDeploymentManager}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasDeploymentManagerAdapter() {
		if (wasDeploymentManagerItemProvider == null) {
			wasDeploymentManagerItemProvider = new WasDeploymentManagerItemProvider(this);
		}

		return wasDeploymentManagerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasDeploymentManagerUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasDeploymentManagerUnitItemProvider wasDeploymentManagerUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasDeploymentManagerUnit}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasDeploymentManagerUnitAdapter() {
		if (wasDeploymentManagerUnitItemProvider == null) {
			wasDeploymentManagerUnitItemProvider = new WasDeploymentManagerUnitItemProvider(this);
		}

		return wasDeploymentManagerUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasDeployRoot} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasDeployRootItemProvider wasDeployRootItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasDeployRoot}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasDeployRootAdapter() {
		if (wasDeployRootItemProvider == null) {
			wasDeployRootItemProvider = new WasDeployRootItemProvider(this);
		}

		return wasDeployRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasEarClassloaderPolicyConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasEarClassloaderPolicyConstraintItemProvider wasEarClassloaderPolicyConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasEarClassloaderPolicyConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasEarClassloaderPolicyConstraintAdapter() {
		if (wasEarClassloaderPolicyConstraintItemProvider == null) {
			wasEarClassloaderPolicyConstraintItemProvider = new WasEarClassloaderPolicyConstraintItemProvider(this);
		}

		return wasEarClassloaderPolicyConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WasEndpointListenerConfiguration} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WasEndpointListenerConfigurationItemProvider wasEndpointListenerConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasEndpointListenerConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasEndpointListenerConfigurationAdapter() {
		if (wasEndpointListenerConfigurationItemProvider == null) {
			wasEndpointListenerConfigurationItemProvider = new WasEndpointListenerConfigurationItemProvider(this);
		}

		return wasEndpointListenerConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasEndpointListenerUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasEndpointListenerUnitItemProvider wasEndpointListenerUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasEndpointListenerUnit}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasEndpointListenerUnitAdapter() {
		if (wasEndpointListenerUnitItemProvider == null) {
			wasEndpointListenerUnitItemProvider = new WasEndpointListenerUnitItemProvider(this);
		}

		return wasEndpointListenerUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasHandlerList} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasHandlerListItemProvider wasHandlerListItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasHandlerList}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasHandlerListAdapter() {
		if (wasHandlerListItemProvider == null) {
			wasHandlerListItemProvider = new WasHandlerListItemProvider(this);
		}

		return wasHandlerListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WASJ2CAuthenticationDataEntry} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WASJ2CAuthenticationDataEntryItemProvider wasj2CAuthenticationDataEntryItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WASJ2CAuthenticationDataEntry}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWASJ2CAuthenticationDataEntryAdapter() {
		if (wasj2CAuthenticationDataEntryItemProvider == null) {
			wasj2CAuthenticationDataEntryItemProvider = new WASJ2CAuthenticationDataEntryItemProvider(this);
		}

		return wasj2CAuthenticationDataEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WASJ2CAuthenticationUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WASJ2CAuthenticationUnitItemProvider wasj2CAuthenticationUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WASJ2CAuthenticationUnit}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWASJ2CAuthenticationUnitAdapter() {
		if (wasj2CAuthenticationUnitItemProvider == null) {
			wasj2CAuthenticationUnitItemProvider = new WASJ2CAuthenticationUnitItemProvider(this);
		}

		return wasj2CAuthenticationUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasJ2EEConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasJ2EEConstraintItemProvider wasJ2EEConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasJ2EEConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasJ2EEConstraintAdapter() {
		if (wasJ2EEConstraintItemProvider == null) {
			wasJ2EEConstraintItemProvider = new WasJ2EEConstraintItemProvider(this);
		}

		return wasJ2EEConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasJ2EEServer} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasJ2EEServerItemProvider wasJ2EEServerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasJ2EEServer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasJ2EEServerAdapter() {
		if (wasJ2EEServerItemProvider == null) {
			wasJ2EEServerItemProvider = new WasJ2EEServerItemProvider(this);
		}

		return wasJ2EEServerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WasJMSActivationSpecification} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WasJMSActivationSpecificationItemProvider wasJMSActivationSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasJMSActivationSpecification}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasJMSActivationSpecificationAdapter() {
		if (wasJMSActivationSpecificationItemProvider == null) {
			wasJMSActivationSpecificationItemProvider = new WasJMSActivationSpecificationItemProvider(this);
		}

		return wasJMSActivationSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WasJMSActivationSpecificationUnit} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WasJMSActivationSpecificationUnitItemProvider wasJMSActivationSpecificationUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasJMSActivationSpecificationUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasJMSActivationSpecificationUnitAdapter() {
		if (wasJMSActivationSpecificationUnitItemProvider == null) {
			wasJMSActivationSpecificationUnitItemProvider = new WasJMSActivationSpecificationUnitItemProvider(this);
		}

		return wasJMSActivationSpecificationUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasJNDIBindingConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasJNDIBindingConstraintItemProvider wasJNDIBindingConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasJNDIBindingConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasJNDIBindingConstraintAdapter() {
		if (wasJNDIBindingConstraintItemProvider == null) {
			wasJNDIBindingConstraintItemProvider = new WasJNDIBindingConstraintItemProvider(this);
		}

		return wasJNDIBindingConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasLdapConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasLdapConfigurationItemProvider wasLdapConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasLdapConfiguration}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasLdapConfigurationAdapter() {
		if (wasLdapConfigurationItemProvider == null) {
			wasLdapConfigurationItemProvider = new WasLdapConfigurationItemProvider(this);
		}

		return wasLdapConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasLdapConfigurationUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasLdapConfigurationUnitItemProvider wasLdapConfigurationUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasLdapConfigurationUnit}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasLdapConfigurationUnitAdapter() {
		if (wasLdapConfigurationUnitItemProvider == null) {
			wasLdapConfigurationUnitItemProvider = new WasLdapConfigurationUnitItemProvider(this);
		}

		return wasLdapConfigurationUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasMessagingEngine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasMessagingEngineItemProvider wasMessagingEngineItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasMessagingEngine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasMessagingEngineAdapter() {
		if (wasMessagingEngineItemProvider == null) {
			wasMessagingEngineItemProvider = new WasMessagingEngineItemProvider(this);
		}

		return wasMessagingEngineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasMessagingEngineUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasMessagingEngineUnitItemProvider wasMessagingEngineUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasMessagingEngineUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasMessagingEngineUnitAdapter() {
		if (wasMessagingEngineUnitItemProvider == null) {
			wasMessagingEngineUnitItemProvider = new WasMessagingEngineUnitItemProvider(this);
		}

		return wasMessagingEngineUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasModuleClassLoaderPolicy} instances.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasModuleClassLoaderPolicyItemProvider wasModuleClassLoaderPolicyItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasModuleClassLoaderPolicy}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasModuleClassLoaderPolicyAdapter() {
		if (wasModuleClassLoaderPolicyItemProvider == null) {
			wasModuleClassLoaderPolicyItemProvider = new WasModuleClassLoaderPolicyItemProvider(this);
		}

		return wasModuleClassLoaderPolicyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasModuleClassloaderPolicyConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasModuleClassloaderPolicyConstraintItemProvider wasModuleClassloaderPolicyConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasModuleClassloaderPolicyConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasModuleClassloaderPolicyConstraintAdapter() {
		if (wasModuleClassloaderPolicyConstraintItemProvider == null) {
			wasModuleClassloaderPolicyConstraintItemProvider = new WasModuleClassloaderPolicyConstraintItemProvider(this);
		}

		return wasModuleClassloaderPolicyConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasModuleStartWeightConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasModuleStartWeightConstraintItemProvider wasModuleStartWeightConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasModuleStartWeightConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasModuleStartWeightConstraintAdapter() {
		if (wasModuleStartWeightConstraintItemProvider == null) {
			wasModuleStartWeightConstraintItemProvider = new WasModuleStartWeightConstraintItemProvider(this);
		}

		return wasModuleStartWeightConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasNode} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasNodeItemProvider wasNodeItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasNode}.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasNodeAdapter() {
		if (wasNodeItemProvider == null) {
			wasNodeItemProvider = new WasNodeItemProvider(this);
		}

		return wasNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasNodeGroup} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasNodeGroupItemProvider wasNodeGroupItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasNodeGroup}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasNodeGroupAdapter() {
		if (wasNodeGroupItemProvider == null) {
			wasNodeGroupItemProvider = new WasNodeGroupItemProvider(this);
		}

		return wasNodeGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasNodeGroupUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasNodeGroupUnitItemProvider wasNodeGroupUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasNodeGroupUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasNodeGroupUnitAdapter() {
		if (wasNodeGroupUnitItemProvider == null) {
			wasNodeGroupUnitItemProvider = new WasNodeGroupUnitItemProvider(this);
		}

		return wasNodeGroupUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasNodeUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasNodeUnitItemProvider wasNodeUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasNodeUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasNodeUnitAdapter() {
		if (wasNodeUnitItemProvider == null) {
			wasNodeUnitItemProvider = new WasNodeUnitItemProvider(this);
		}

		return wasNodeUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasNodeWindowsServiceUnit} instances.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasNodeWindowsServiceUnitItemProvider wasNodeWindowsServiceUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasNodeWindowsServiceUnit}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasNodeWindowsServiceUnitAdapter() {
		if (wasNodeWindowsServiceUnitItemProvider == null) {
			wasNodeWindowsServiceUnitItemProvider = new WasNodeWindowsServiceUnitItemProvider(this);
		}

		return wasNodeWindowsServiceUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasPluginAdmin} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasPluginAdminItemProvider wasPluginAdminItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasPluginAdmin}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasPluginAdminAdapter() {
		if (wasPluginAdminItemProvider == null) {
			wasPluginAdminItemProvider = new WasPluginAdminItemProvider(this);
		}

		return wasPluginAdminItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasPluginRedirection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasPluginRedirectionItemProvider wasPluginRedirectionItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasPluginRedirection}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasPluginRedirectionAdapter() {
		if (wasPluginRedirectionItemProvider == null) {
			wasPluginRedirectionItemProvider = new WasPluginRedirectionItemProvider(this);
		}

		return wasPluginRedirectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSecurity} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasSecurityItemProvider wasSecurityItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSecurity}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSecurityAdapter() {
		if (wasSecurityItemProvider == null) {
			wasSecurityItemProvider = new WasSecurityItemProvider(this);
		}

		return wasSecurityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSecuritySubject} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasSecuritySubjectItemProvider wasSecuritySubjectItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSecuritySubject}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSecuritySubjectAdapter() {
		if (wasSecuritySubjectItemProvider == null) {
			wasSecuritySubjectItemProvider = new WasSecuritySubjectItemProvider(this);
		}

		return wasSecuritySubjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSecuritySubjectConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSecuritySubjectConstraintItemProvider wasSecuritySubjectConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSecuritySubjectConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasSecuritySubjectConstraintAdapter() {
		if (wasSecuritySubjectConstraintItemProvider == null) {
			wasSecuritySubjectConstraintItemProvider = new WasSecuritySubjectConstraintItemProvider(this);
		}

		return wasSecuritySubjectConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasServer} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasServerItemProvider wasServerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasServer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasServerAdapter() {
		if (wasServerItemProvider == null) {
			wasServerItemProvider = new WasServerItemProvider(this);
		}

		return wasServerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSharedLibContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSharedLibContainerItemProvider wasSharedLibContainerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSharedLibContainer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSharedLibContainerAdapter() {
		if (wasSharedLibContainerItemProvider == null) {
			wasSharedLibContainerItemProvider = new WasSharedLibContainerItemProvider(this);
		}

		return wasSharedLibContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSharedLibraryEntryUnit} instances.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSharedLibraryEntryUnitItemProvider wasSharedLibraryEntryUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSharedLibraryEntryUnit}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasSharedLibraryEntryUnitAdapter() {
		if (wasSharedLibraryEntryUnitItemProvider == null) {
			wasSharedLibraryEntryUnitItemProvider = new WasSharedLibraryEntryUnitItemProvider(this);
		}

		return wasSharedLibraryEntryUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibDestination} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasSibDestinationItemProvider wasSibDestinationItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibDestination}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSibDestinationAdapter() {
		if (wasSibDestinationItemProvider == null) {
			wasSibDestinationItemProvider = new WasSibDestinationItemProvider(this);
		}

		return wasSibDestinationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibDestinationUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSibDestinationUnitItemProvider wasSibDestinationUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibDestinationUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSibDestinationUnitAdapter() {
		if (wasSibDestinationUnitItemProvider == null) {
			wasSibDestinationUnitItemProvider = new WasSibDestinationUnitItemProvider(this);
		}

		return wasSibDestinationUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibForeignBus} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasSibForeignBusItemProvider wasSibForeignBusItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibForeignBus}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSibForeignBusAdapter() {
		if (wasSibForeignBusItemProvider == null) {
			wasSibForeignBusItemProvider = new WasSibForeignBusItemProvider(this);
		}

		return wasSibForeignBusItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibInboundPort} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasSibInboundPortItemProvider wasSibInboundPortItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibInboundPort}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSibInboundPortAdapter() {
		if (wasSibInboundPortItemProvider == null) {
			wasSibInboundPortItemProvider = new WasSibInboundPortItemProvider(this);
		}

		return wasSibInboundPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibInboundPortUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSibInboundPortUnitItemProvider wasSibInboundPortUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibInboundPortUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSibInboundPortUnitAdapter() {
		if (wasSibInboundPortUnitItemProvider == null) {
			wasSibInboundPortUnitItemProvider = new WasSibInboundPortUnitItemProvider(this);
		}

		return wasSibInboundPortUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibInboundService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSibInboundServiceItemProvider wasSibInboundServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibInboundService}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSibInboundServiceAdapter() {
		if (wasSibInboundServiceItemProvider == null) {
			wasSibInboundServiceItemProvider = new WasSibInboundServiceItemProvider(this);
		}

		return wasSibInboundServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibInboundServiceUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSibInboundServiceUnitItemProvider wasSibInboundServiceUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibInboundServiceUnit}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasSibInboundServiceUnitAdapter() {
		if (wasSibInboundServiceUnitItemProvider == null) {
			wasSibInboundServiceUnitItemProvider = new WasSibInboundServiceUnitItemProvider(this);
		}

		return wasSibInboundServiceUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibMediation} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasSibMediationItemProvider wasSibMediationItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibMediation}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSibMediationAdapter() {
		if (wasSibMediationItemProvider == null) {
			wasSibMediationItemProvider = new WasSibMediationItemProvider(this);
		}

		return wasSibMediationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibMediationUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasSibMediationUnitItemProvider wasSibMediationUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibMediationUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSibMediationUnitAdapter() {
		if (wasSibMediationUnitItemProvider == null) {
			wasSibMediationUnitItemProvider = new WasSibMediationUnitItemProvider(this);
		}

		return wasSibMediationUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibOutboundPort} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasSibOutboundPortItemProvider wasSibOutboundPortItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibOutboundPort}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSibOutboundPortAdapter() {
		if (wasSibOutboundPortItemProvider == null) {
			wasSibOutboundPortItemProvider = new WasSibOutboundPortItemProvider(this);
		}

		return wasSibOutboundPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibOutboundPortUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSibOutboundPortUnitItemProvider wasSibOutboundPortUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibOutboundPortUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSibOutboundPortUnitAdapter() {
		if (wasSibOutboundPortUnitItemProvider == null) {
			wasSibOutboundPortUnitItemProvider = new WasSibOutboundPortUnitItemProvider(this);
		}

		return wasSibOutboundPortUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibOutboundService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSibOutboundServiceItemProvider wasSibOutboundServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibOutboundService}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSibOutboundServiceAdapter() {
		if (wasSibOutboundServiceItemProvider == null) {
			wasSibOutboundServiceItemProvider = new WasSibOutboundServiceItemProvider(this);
		}

		return wasSibOutboundServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSibOutboundServiceUnit} instances.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSibOutboundServiceUnitItemProvider wasSibOutboundServiceUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibOutboundServiceUnit}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasSibOutboundServiceUnitAdapter() {
		if (wasSibOutboundServiceUnitItemProvider == null) {
			wasSibOutboundServiceUnitItemProvider = new WasSibOutboundServiceUnitItemProvider(this);
		}

		return wasSibOutboundServiceUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.was.WasSibServiceIntegrationBusLink} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WasSibServiceIntegrationBusLinkItemProvider wasSibServiceIntegrationBusLinkItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSibServiceIntegrationBusLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasSibServiceIntegrationBusLinkAdapter() {
		if (wasSibServiceIntegrationBusLinkItemProvider == null) {
			wasSibServiceIntegrationBusLinkItemProvider = new WasSibServiceIntegrationBusLinkItemProvider(this);
		}

		return wasSibServiceIntegrationBusLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSIBus} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSIBusItemProvider wasSIBusItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSIBus}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSIBusAdapter() {
		if (wasSIBusItemProvider == null) {
			wasSIBusItemProvider = new WasSIBusItemProvider(this);
		}

		return wasSIBusItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSIBusUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasSIBusUnitItemProvider wasSIBusUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSIBusUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSIBusUnitAdapter() {
		if (wasSIBusUnitItemProvider == null) {
			wasSIBusUnitItemProvider = new WasSIBusUnitItemProvider(this);
		}

		return wasSIBusUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSubstitutionVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSubstitutionVariableItemProvider wasSubstitutionVariableItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSubstitutionVariable}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasSubstitutionVariableAdapter() {
		if (wasSubstitutionVariableItemProvider == null) {
			wasSubstitutionVariableItemProvider = new WasSubstitutionVariableItemProvider(this);
		}

		return wasSubstitutionVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSystem} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WasSystemItemProvider wasSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSystem}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSystemAdapter() {
		if (wasSystemItemProvider == null) {
			wasSystemItemProvider = new WasSystemItemProvider(this);
		}

		return wasSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasSystemUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasSystemUnitItemProvider wasSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasSystemUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasSystemUnitAdapter() {
		if (wasSystemUnitItemProvider == null) {
			wasSystemUnitItemProvider = new WasSystemUnitItemProvider(this);
		}

		return wasSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasV4Datasource} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasV4DatasourceItemProvider wasV4DatasourceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasV4Datasource}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasV4DatasourceAdapter() {
		if (wasV4DatasourceItemProvider == null) {
			wasV4DatasourceItemProvider = new WasV4DatasourceItemProvider(this);
		}

		return wasV4DatasourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasV5Datasource} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasV5DatasourceItemProvider wasV5DatasourceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasV5Datasource}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasV5DatasourceAdapter() {
		if (wasV5DatasourceItemProvider == null) {
			wasV5DatasourceItemProvider = new WasV5DatasourceItemProvider(this);
		}

		return wasV5DatasourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasV5DB2Datasource} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasV5DB2DatasourceItemProvider wasV5DB2DatasourceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasV5DB2Datasource}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasV5DB2DatasourceAdapter() {
		if (wasV5DB2DatasourceItemProvider == null) {
			wasV5DB2DatasourceItemProvider = new WasV5DB2DatasourceItemProvider(this);
		}

		return wasV5DB2DatasourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasV5DB2ZosDatasource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasV5DB2ZosDatasourceItemProvider wasV5DB2ZosDatasourceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasV5DB2ZosDatasource}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasV5DB2ZosDatasourceAdapter() {
		if (wasV5DB2ZosDatasourceItemProvider == null) {
			wasV5DB2ZosDatasourceItemProvider = new WasV5DB2ZosDatasourceItemProvider(this);
		}

		return wasV5DB2ZosDatasourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasWarClassloaderPolicyConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasWarClassloaderPolicyConstraintItemProvider wasWarClassloaderPolicyConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasWarClassloaderPolicyConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWasWarClassloaderPolicyConstraintAdapter() {
		if (wasWarClassloaderPolicyConstraintItemProvider == null) {
			wasWarClassloaderPolicyConstraintItemProvider = new WasWarClassloaderPolicyConstraintItemProvider(this);
		}

		return wasWarClassloaderPolicyConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasWebAppExt} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasWebAppExtItemProvider wasWebAppExtItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasWebAppExt}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasWebAppExtAdapter() {
		if (wasWebAppExtItemProvider == null) {
			wasWebAppExtItemProvider = new WasWebAppExtItemProvider(this);
		}

		return wasWebAppExtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasWebServer} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasWebServerItemProvider wasWebServerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasWebServer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasWebServerAdapter() {
		if (wasWebServerItemProvider == null) {
			wasWebServerItemProvider = new WasWebServerItemProvider(this);
		}

		return wasWebServerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasWebServerManagement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WasWebServerManagementItemProvider wasWebServerManagementItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasWebServerManagement}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasWebServerManagementAdapter() {
		if (wasWebServerManagementItemProvider == null) {
			wasWebServerManagementItemProvider = new WasWebServerManagementItemProvider(this);
		}

		return wasWebServerManagementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasWebServerPlugin} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasWebServerPluginItemProvider wasWebServerPluginItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasWebServerPlugin}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasWebServerPluginAdapter() {
		if (wasWebServerPluginItemProvider == null) {
			wasWebServerPluginItemProvider = new WasWebServerPluginItemProvider(this);
		}

		return wasWebServerPluginItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WasWebServerUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WasWebServerUnitItemProvider wasWebServerUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WasWebServerUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWasWebServerUnitAdapter() {
		if (wasWebServerUnitItemProvider == null) {
			wasWebServerUnitItemProvider = new WasWebServerUnitItemProvider(this);
		}

		return wasWebServerUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.was.WebsphereAppServerUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WebsphereAppServerUnitItemProvider websphereAppServerUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.was.WebsphereAppServerUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWebsphereAppServerUnitAdapter() {
		if (websphereAppServerUnitItemProvider == null) {
			websphereAppServerUnitItemProvider = new WebsphereAppServerUnitItemProvider(this);
		}

		return websphereAppServerUnitItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class) || (((Class)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (classloaderItemProvider != null) classloaderItemProvider.dispose();
		if (db2JdbcProviderItemProvider != null) db2JdbcProviderItemProvider.dispose();
		if (db2JdbcProviderUnitItemProvider != null) db2JdbcProviderUnitItemProvider.dispose();
		if (derbyJdbcProviderItemProvider != null) derbyJdbcProviderItemProvider.dispose();
		if (derbyJdbcProviderUnitItemProvider != null) derbyJdbcProviderUnitItemProvider.dispose();
		if (extendedJdbcProviderItemProvider != null) extendedJdbcProviderItemProvider.dispose();
		if (extendedJdbcProviderUnitItemProvider != null) extendedJdbcProviderUnitItemProvider.dispose();
		if (hostNameAliasTypeItemProvider != null) hostNameAliasTypeItemProvider.dispose();
		if (sharedLibraryEntryItemProvider != null) sharedLibraryEntryItemProvider.dispose();
		if (virtualHostTypeItemProvider != null) virtualHostTypeItemProvider.dispose();
		if (wasAdvancedLdapConfigurationItemProvider != null) wasAdvancedLdapConfigurationItemProvider.dispose();
		if (wasApplicationClassLoaderPolicyItemProvider != null) wasApplicationClassLoaderPolicyItemProvider.dispose();
		if (wasApplicationExtItemProvider != null) wasApplicationExtItemProvider.dispose();
		if (wasApplicationServerClassLoaderPolicyItemProvider != null) wasApplicationServerClassLoaderPolicyItemProvider.dispose();
		if (wasCellItemProvider != null) wasCellItemProvider.dispose();
		if (wasCellUnitItemProvider != null) wasCellUnitItemProvider.dispose();
		if (wasClassLoaderConfigurationUnitItemProvider != null) wasClassLoaderConfigurationUnitItemProvider.dispose();
		if (wasClassLoaderPolicyItemProvider != null) wasClassLoaderPolicyItemProvider.dispose();
		if (wasClusterItemProvider != null) wasClusterItemProvider.dispose();
		if (wasClusterUnitItemProvider != null) wasClusterUnitItemProvider.dispose();
		if (wasConfigurationContainerItemProvider != null) wasConfigurationContainerItemProvider.dispose();
		if (wasDatasourceItemProvider != null) wasDatasourceItemProvider.dispose();
		if (wasDatasourceUnitItemProvider != null) wasDatasourceUnitItemProvider.dispose();
		if (wasDefaultMessagingConnectionFactoryConfigurationItemProvider != null) wasDefaultMessagingConnectionFactoryConfigurationItemProvider.dispose();
		if (wasDefaultMessagingConnectionFactoryUnitItemProvider != null) wasDefaultMessagingConnectionFactoryUnitItemProvider.dispose();
		if (wasDefaultMessagingQueueConnectionFactoryConfigurationItemProvider != null) wasDefaultMessagingQueueConnectionFactoryConfigurationItemProvider.dispose();
		if (wasDefaultMessagingQueueConnectionFactoryUnitItemProvider != null) wasDefaultMessagingQueueConnectionFactoryUnitItemProvider.dispose();
		if (wasDefaultMessagingQueueDestinationItemProvider != null) wasDefaultMessagingQueueDestinationItemProvider.dispose();
		if (wasDefaultMessagingQueueDestinationUnitItemProvider != null) wasDefaultMessagingQueueDestinationUnitItemProvider.dispose();
		if (wasDefaultMessagingTopicConnectionFactoryConfigurationItemProvider != null) wasDefaultMessagingTopicConnectionFactoryConfigurationItemProvider.dispose();
		if (wasDefaultMessagingTopicConnectionFactoryUnitItemProvider != null) wasDefaultMessagingTopicConnectionFactoryUnitItemProvider.dispose();
		if (wasDefaultMessagingTopicDestinationItemProvider != null) wasDefaultMessagingTopicDestinationItemProvider.dispose();
		if (wasDefaultMessagingTopicDestinationUnitItemProvider != null) wasDefaultMessagingTopicDestinationUnitItemProvider.dispose();
		if (wasDeploymentManagerItemProvider != null) wasDeploymentManagerItemProvider.dispose();
		if (wasDeploymentManagerUnitItemProvider != null) wasDeploymentManagerUnitItemProvider.dispose();
		if (wasDeployRootItemProvider != null) wasDeployRootItemProvider.dispose();
		if (wasEarClassloaderPolicyConstraintItemProvider != null) wasEarClassloaderPolicyConstraintItemProvider.dispose();
		if (wasEndpointListenerConfigurationItemProvider != null) wasEndpointListenerConfigurationItemProvider.dispose();
		if (wasEndpointListenerUnitItemProvider != null) wasEndpointListenerUnitItemProvider.dispose();
		if (wasHandlerListItemProvider != null) wasHandlerListItemProvider.dispose();
		if (wasj2CAuthenticationDataEntryItemProvider != null) wasj2CAuthenticationDataEntryItemProvider.dispose();
		if (wasj2CAuthenticationUnitItemProvider != null) wasj2CAuthenticationUnitItemProvider.dispose();
		if (wasJ2EEConstraintItemProvider != null) wasJ2EEConstraintItemProvider.dispose();
		if (wasJ2EEServerItemProvider != null) wasJ2EEServerItemProvider.dispose();
		if (wasJMSActivationSpecificationItemProvider != null) wasJMSActivationSpecificationItemProvider.dispose();
		if (wasJMSActivationSpecificationUnitItemProvider != null) wasJMSActivationSpecificationUnitItemProvider.dispose();
		if (wasJNDIBindingConstraintItemProvider != null) wasJNDIBindingConstraintItemProvider.dispose();
		if (wasLdapConfigurationItemProvider != null) wasLdapConfigurationItemProvider.dispose();
		if (wasLdapConfigurationUnitItemProvider != null) wasLdapConfigurationUnitItemProvider.dispose();
		if (wasMessagingEngineItemProvider != null) wasMessagingEngineItemProvider.dispose();
		if (wasMessagingEngineUnitItemProvider != null) wasMessagingEngineUnitItemProvider.dispose();
		if (wasModuleClassLoaderPolicyItemProvider != null) wasModuleClassLoaderPolicyItemProvider.dispose();
		if (wasModuleClassloaderPolicyConstraintItemProvider != null) wasModuleClassloaderPolicyConstraintItemProvider.dispose();
		if (wasModuleStartWeightConstraintItemProvider != null) wasModuleStartWeightConstraintItemProvider.dispose();
		if (wasNodeItemProvider != null) wasNodeItemProvider.dispose();
		if (wasNodeGroupItemProvider != null) wasNodeGroupItemProvider.dispose();
		if (wasNodeGroupUnitItemProvider != null) wasNodeGroupUnitItemProvider.dispose();
		if (wasNodeUnitItemProvider != null) wasNodeUnitItemProvider.dispose();
		if (wasNodeWindowsServiceUnitItemProvider != null) wasNodeWindowsServiceUnitItemProvider.dispose();
		if (wasPluginAdminItemProvider != null) wasPluginAdminItemProvider.dispose();
		if (wasPluginRedirectionItemProvider != null) wasPluginRedirectionItemProvider.dispose();
		if (wasSecurityItemProvider != null) wasSecurityItemProvider.dispose();
		if (wasSecuritySubjectItemProvider != null) wasSecuritySubjectItemProvider.dispose();
		if (wasSecuritySubjectConstraintItemProvider != null) wasSecuritySubjectConstraintItemProvider.dispose();
		if (wasServerItemProvider != null) wasServerItemProvider.dispose();
		if (wasSharedLibContainerItemProvider != null) wasSharedLibContainerItemProvider.dispose();
		if (wasSharedLibraryEntryUnitItemProvider != null) wasSharedLibraryEntryUnitItemProvider.dispose();
		if (wasSibDestinationItemProvider != null) wasSibDestinationItemProvider.dispose();
		if (wasSibDestinationUnitItemProvider != null) wasSibDestinationUnitItemProvider.dispose();
		if (wasSibForeignBusItemProvider != null) wasSibForeignBusItemProvider.dispose();
		if (wasSibInboundPortItemProvider != null) wasSibInboundPortItemProvider.dispose();
		if (wasSibInboundPortUnitItemProvider != null) wasSibInboundPortUnitItemProvider.dispose();
		if (wasSibInboundServiceItemProvider != null) wasSibInboundServiceItemProvider.dispose();
		if (wasSibInboundServiceUnitItemProvider != null) wasSibInboundServiceUnitItemProvider.dispose();
		if (wasSibMediationItemProvider != null) wasSibMediationItemProvider.dispose();
		if (wasSibMediationUnitItemProvider != null) wasSibMediationUnitItemProvider.dispose();
		if (wasSibOutboundPortItemProvider != null) wasSibOutboundPortItemProvider.dispose();
		if (wasSibOutboundPortUnitItemProvider != null) wasSibOutboundPortUnitItemProvider.dispose();
		if (wasSibOutboundServiceItemProvider != null) wasSibOutboundServiceItemProvider.dispose();
		if (wasSibOutboundServiceUnitItemProvider != null) wasSibOutboundServiceUnitItemProvider.dispose();
		if (wasSibServiceIntegrationBusLinkItemProvider != null) wasSibServiceIntegrationBusLinkItemProvider.dispose();
		if (wasSIBusItemProvider != null) wasSIBusItemProvider.dispose();
		if (wasSIBusUnitItemProvider != null) wasSIBusUnitItemProvider.dispose();
		if (wasSubstitutionVariableItemProvider != null) wasSubstitutionVariableItemProvider.dispose();
		if (wasSystemItemProvider != null) wasSystemItemProvider.dispose();
		if (wasSystemUnitItemProvider != null) wasSystemUnitItemProvider.dispose();
		if (wasV4DatasourceItemProvider != null) wasV4DatasourceItemProvider.dispose();
		if (wasV5DatasourceItemProvider != null) wasV5DatasourceItemProvider.dispose();
		if (wasV5DB2DatasourceItemProvider != null) wasV5DB2DatasourceItemProvider.dispose();
		if (wasV5DB2ZosDatasourceItemProvider != null) wasV5DB2ZosDatasourceItemProvider.dispose();
		if (wasWarClassloaderPolicyConstraintItemProvider != null) wasWarClassloaderPolicyConstraintItemProvider.dispose();
		if (wasWebAppExtItemProvider != null) wasWebAppExtItemProvider.dispose();
		if (wasWebServerItemProvider != null) wasWebServerItemProvider.dispose();
		if (wasWebServerManagementItemProvider != null) wasWebServerManagementItemProvider.dispose();
		if (wasWebServerPluginItemProvider != null) wasWebServerPluginItemProvider.dispose();
		if (wasWebServerUnitItemProvider != null) wasWebServerUnitItemProvider.dispose();
		if (websphereAppServerUnitItemProvider != null) websphereAppServerUnitItemProvider.dispose();
	}

}
