/*******************************************************************************
 * Copyright (c) 2003, 2007 IBM Corporation Licensed Material - Property of IBM. All rights reserved.
 *  
 * US Government Users Restricted Rights - Use, duplication or disclosure v1.0 restricted by GSA ADP
 * Schedule Contract with IBM Corp.
 * 
 * Contributors: IBM Corporation - initial API and implementation
 *******************************************************************************/
package com.ibm.ccl.soa.deploy.database.validation;

import org.eclipse.emf.common.util.EMap;
import org.eclipse.emf.ecore.util.FeatureMap;

import com.ibm.ccl.soa.deploy.database.DDLArtifact;
import com.ibm.ccl.soa.deploy.database.DDLInterface;
import com.ibm.ccl.soa.deploy.database.DMLArtifact;
import com.ibm.ccl.soa.deploy.database.Database;
import com.ibm.ccl.soa.deploy.database.DatabaseComponent;
import com.ibm.ccl.soa.deploy.database.DatabaseDefinition;
import com.ibm.ccl.soa.deploy.database.DatabaseInstance;
import com.ibm.ccl.soa.deploy.database.DatabaseInstanceUnit;
import com.ibm.ccl.soa.deploy.database.DatabaseUnit;
import com.ibm.ccl.soa.deploy.database.SQLModule;
import com.ibm.ccl.soa.deploy.database.SQLUser;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.database.DatabaseDeployRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DatabaseDeployRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);

	boolean validateXMLNSPrefixMap(EMap value);

	boolean validateXSISchemaLocation(EMap value);

	boolean validateArtifactDdl(DDLArtifact value);

	boolean validateArtifactDml(DMLArtifact value);

	boolean validateCapabilityDatabase(Database value);

	boolean validateCapabilityDatabaseInstance(DatabaseInstance value);

	boolean validateCapabilitySqlUser(SQLUser value);

	boolean validateComponentDatabase(DatabaseComponent value);

	boolean validateInterfaceDdl(DDLInterface value);

	boolean validateServiceDatabaseDefinition(DatabaseDefinition value);

	boolean validateUnitDatabaseInstanceUnit(DatabaseInstanceUnit value);

	boolean validateUnitDatabaseUnit(DatabaseUnit value);

	boolean validateUnitSQLModule(SQLModule value);
}
