/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.ibm.ccl.soa.deploy.tds.validation;

import java.util.Map;

import org.eclipse.emf.ecore.util.FeatureMap;

import com.ibm.ccl.soa.deploy.tds.TdsBaseSystem;
import com.ibm.ccl.soa.deploy.tds.TdsBaseSystemUnit;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.tds.TDSRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TDSRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateXMLNSPrefixMap(EMap<String, String> value);

	boolean validateXSISchemaLocation(EMap<String, String> value);

	boolean validateXMLNSPrefixMap(Map value);
	boolean validateXSISchemaLocation(Map value);
	boolean validateCapabilityTdsBaseSystem(TdsBaseSystem value);
	boolean validateUnitTdsBaseSystemUnit(TdsBaseSystemUnit value);
}
