/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.ibm.ccl.soa.deploy.osgi.validation;

import java.util.List;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.osgi.ExportedPackage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExportedPackageValidator {
	boolean validate();

	boolean validateFriend(List value);
	boolean validateInternal(boolean value);
}
