/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.ibm.ccl.soa.deploy.osgi.validation;

import com.ibm.ccl.soa.deploy.osgi.BundleCapability;
import com.ibm.ccl.soa.deploy.osgi.BundleComponent;
import com.ibm.ccl.soa.deploy.osgi.ExportedPackage;
import com.ibm.ccl.soa.deploy.osgi.Library;

import java.util.Map;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.osgi.OSGiRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OSGiRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateXMLNSPrefixMap(Map value);
	boolean validateXSISchemaLocation(Map value);
	boolean validateCapabilityApiPackage(ExportedPackage value);
	boolean validateCapabilityOsgiBundle(BundleCapability value);
	boolean validateComponentBundle(BundleComponent value);
	boolean validateUnitOsgiLibrary(Library value);
}
