/*******************************************************************************
 * Copyright (c) 2003, 2007 IBM Corporation Licensed Material - Property of IBM. All rights reserved.
 *  
 * US Government Users Restricted Rights - Use, duplication or disclosure v1.0 restricted by GSA ADP
 * Schedule Contract with IBM Corp.
 * 
 * Contributors: IBM Corporation - initial API and implementation
 *******************************************************************************/
package com.ibm.ccl.soa.deploy.os.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import com.ibm.ccl.soa.deploy.os.util.OsAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc --> <!--
 * end-user-doc -->
 * @generated
 */
public class OsItemProviderAdapterFactory extends OsAdapterFactory implements
		ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public static final String copyright = "Copyright (c) 2005, 2006 IBM Corporation. Licensed Material - Property of IBM. All rights reserved."; //$NON-NLS-1$

	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection supportedTypes = new ArrayList();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public OsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.AIXLocalGroup} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected AIXLocalGroupItemProvider aixLocalGroupItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.AIXLocalGroup}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createAIXLocalGroupAdapter() {
		if (aixLocalGroupItemProvider == null) {
			aixLocalGroupItemProvider = new AIXLocalGroupItemProvider(this);
		}

		return aixLocalGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.AIXLocalGroupUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected AIXLocalGroupUnitItemProvider aixLocalGroupUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.AIXLocalGroupUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createAIXLocalGroupUnitAdapter() {
		if (aixLocalGroupUnitItemProvider == null) {
			aixLocalGroupUnitItemProvider = new AIXLocalGroupUnitItemProvider(this);
		}

		return aixLocalGroupUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.AIXLocalService} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected AIXLocalServiceItemProvider aixLocalServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.AIXLocalService}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createAIXLocalServiceAdapter() {
		if (aixLocalServiceItemProvider == null) {
			aixLocalServiceItemProvider = new AIXLocalServiceItemProvider(this);
		}

		return aixLocalServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.AIXLocalServiceUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected AIXLocalServiceUnitItemProvider aixLocalServiceUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.AIXLocalServiceUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createAIXLocalServiceUnitAdapter() {
		if (aixLocalServiceUnitItemProvider == null) {
			aixLocalServiceUnitItemProvider = new AIXLocalServiceUnitItemProvider(this);
		}

		return aixLocalServiceUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.AIXLocalUser} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected AIXLocalUserItemProvider aixLocalUserItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.AIXLocalUser}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createAIXLocalUserAdapter() {
		if (aixLocalUserItemProvider == null) {
			aixLocalUserItemProvider = new AIXLocalUserItemProvider(this);
		}

		return aixLocalUserItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.AIXLocalUserUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected AIXLocalUserUnitItemProvider aixLocalUserUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.AIXLocalUserUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createAIXLocalUserUnitAdapter() {
		if (aixLocalUserUnitItemProvider == null) {
			aixLocalUserUnitItemProvider = new AIXLocalUserUnitItemProvider(this);
		}

		return aixLocalUserUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.AIXOperatingSystem} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected AIXOperatingSystemItemProvider aixOperatingSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.AIXOperatingSystem}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createAIXOperatingSystemAdapter() {
		if (aixOperatingSystemItemProvider == null) {
			aixOperatingSystemItemProvider = new AIXOperatingSystemItemProvider(this);
		}

		return aixOperatingSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.AIXOperatingSystemUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIXOperatingSystemUnitItemProvider aixOperatingSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.AIXOperatingSystemUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createAIXOperatingSystemUnitAdapter() {
		if (aixOperatingSystemUnitItemProvider == null) {
			aixOperatingSystemUnitItemProvider = new AIXOperatingSystemUnitItemProvider(this);
		}

		return aixOperatingSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.DataFile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataFileItemProvider dataFileItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.DataFile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDataFileAdapter() {
		if (dataFileItemProvider == null) {
			dataFileItemProvider = new DataFileItemProvider(this);
		}

		return dataFileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.DataFileUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataFileUnitItemProvider dataFileUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.DataFileUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDataFileUnitAdapter() {
		if (dataFileUnitItemProvider == null) {
			dataFileUnitItemProvider = new DataFileUnitItemProvider(this);
		}

		return dataFileUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.Directory} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected DirectoryItemProvider directoryItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.Directory}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createDirectoryAdapter() {
		if (directoryItemProvider == null) {
			directoryItemProvider = new DirectoryItemProvider(this);
		}

		return directoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.DirectoryUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DirectoryUnitItemProvider directoryUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.DirectoryUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDirectoryUnitAdapter() {
		if (directoryUnitItemProvider == null) {
			directoryUnitItemProvider = new DirectoryUnitItemProvider(this);
		}

		return directoryUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.FileSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FileSystemItemProvider fileSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.FileSystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFileSystemAdapter() {
		if (fileSystemItemProvider == null) {
			fileSystemItemProvider = new FileSystemItemProvider(this);
		}

		return fileSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.FileSystemContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FileSystemContentItemProvider fileSystemContentItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.FileSystemContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFileSystemContentAdapter() {
		if (fileSystemContentItemProvider == null) {
			fileSystemContentItemProvider = new FileSystemContentItemProvider(this);
		}

		return fileSystemContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.FileSystemContentUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FileSystemContentUnitItemProvider fileSystemContentUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.FileSystemContentUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFileSystemContentUnitAdapter() {
		if (fileSystemContentUnitItemProvider == null) {
			fileSystemContentUnitItemProvider = new FileSystemContentUnitItemProvider(this);
		}

		return fileSystemContentUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.FileSystemUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FileSystemUnitItemProvider fileSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.FileSystemUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFileSystemUnitAdapter() {
		if (fileSystemUnitItemProvider == null) {
			fileSystemUnitItemProvider = new FileSystemUnitItemProvider(this);
		}

		return fileSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.LinuxLocalGroup} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected LinuxLocalGroupItemProvider linuxLocalGroupItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.LinuxLocalGroup}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createLinuxLocalGroupAdapter() {
		if (linuxLocalGroupItemProvider == null) {
			linuxLocalGroupItemProvider = new LinuxLocalGroupItemProvider(this);
		}

		return linuxLocalGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.LinuxLocalGroupUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected LinuxLocalGroupUnitItemProvider linuxLocalGroupUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.LinuxLocalGroupUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createLinuxLocalGroupUnitAdapter() {
		if (linuxLocalGroupUnitItemProvider == null) {
			linuxLocalGroupUnitItemProvider = new LinuxLocalGroupUnitItemProvider(this);
		}

		return linuxLocalGroupUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.LinuxLocalService} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected LinuxLocalServiceItemProvider linuxLocalServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.LinuxLocalService}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createLinuxLocalServiceAdapter() {
		if (linuxLocalServiceItemProvider == null) {
			linuxLocalServiceItemProvider = new LinuxLocalServiceItemProvider(this);
		}

		return linuxLocalServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.LinuxLocalServiceUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinuxLocalServiceUnitItemProvider linuxLocalServiceUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.LinuxLocalServiceUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createLinuxLocalServiceUnitAdapter() {
		if (linuxLocalServiceUnitItemProvider == null) {
			linuxLocalServiceUnitItemProvider = new LinuxLocalServiceUnitItemProvider(this);
		}

		return linuxLocalServiceUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.LinuxLocalUser} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected LinuxLocalUserItemProvider linuxLocalUserItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.LinuxLocalUser}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createLinuxLocalUserAdapter() {
		if (linuxLocalUserItemProvider == null) {
			linuxLocalUserItemProvider = new LinuxLocalUserItemProvider(this);
		}

		return linuxLocalUserItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.LinuxLocalUserUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected LinuxLocalUserUnitItemProvider linuxLocalUserUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.LinuxLocalUserUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createLinuxLocalUserUnitAdapter() {
		if (linuxLocalUserUnitItemProvider == null) {
			linuxLocalUserUnitItemProvider = new LinuxLocalUserUnitItemProvider(this);
		}

		return linuxLocalUserUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.LinuxOperatingSystem} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected LinuxOperatingSystemItemProvider linuxOperatingSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.LinuxOperatingSystem}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createLinuxOperatingSystemAdapter() {
		if (linuxOperatingSystemItemProvider == null) {
			linuxOperatingSystemItemProvider = new LinuxOperatingSystemItemProvider(this);
		}

		return linuxOperatingSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.LinuxOperatingSystemUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinuxOperatingSystemUnitItemProvider linuxOperatingSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.LinuxOperatingSystemUnit}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLinuxOperatingSystemUnitAdapter() {
		if (linuxOperatingSystemUnitItemProvider == null) {
			linuxOperatingSystemUnitItemProvider = new LinuxOperatingSystemUnitItemProvider(this);
		}

		return linuxOperatingSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.LocalFileSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalFileSystemItemProvider localFileSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.LocalFileSystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLocalFileSystemAdapter() {
		if (localFileSystemItemProvider == null) {
			localFileSystemItemProvider = new LocalFileSystemItemProvider(this);
		}

		return localFileSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.LocalFileSystemUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalFileSystemUnitItemProvider localFileSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.LocalFileSystemUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLocalFileSystemUnitAdapter() {
		if (localFileSystemUnitItemProvider == null) {
			localFileSystemUnitItemProvider = new LocalFileSystemUnitItemProvider(this);
		}

		return localFileSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.NFSFileSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NFSFileSystemItemProvider nfsFileSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.NFSFileSystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createNFSFileSystemAdapter() {
		if (nfsFileSystemItemProvider == null) {
			nfsFileSystemItemProvider = new NFSFileSystemItemProvider(this);
		}

		return nfsFileSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.NFSFileSystemUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NFSFileSystemUnitItemProvider nfsFileSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.NFSFileSystemUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createNFSFileSystemUnitAdapter() {
		if (nfsFileSystemUnitItemProvider == null) {
			nfsFileSystemUnitItemProvider = new NFSFileSystemUnitItemProvider(this);
		}

		return nfsFileSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.OpenVmsFileSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OpenVmsFileSystemItemProvider openVmsFileSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.OpenVmsFileSystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOpenVmsFileSystemAdapter() {
		if (openVmsFileSystemItemProvider == null) {
			openVmsFileSystemItemProvider = new OpenVmsFileSystemItemProvider(this);
		}

		return openVmsFileSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.OpenVmsFileSystemUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OpenVmsFileSystemUnitItemProvider openVmsFileSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.OpenVmsFileSystemUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOpenVmsFileSystemUnitAdapter() {
		if (openVmsFileSystemUnitItemProvider == null) {
			openVmsFileSystemUnitItemProvider = new OpenVmsFileSystemUnitItemProvider(this);
		}

		return openVmsFileSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.OperatingSystem} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected OperatingSystemItemProvider operatingSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.OperatingSystem}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createOperatingSystemAdapter() {
		if (operatingSystemItemProvider == null) {
			operatingSystemItemProvider = new OperatingSystemItemProvider(this);
		}

		return operatingSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.OperatingSystemRoot} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected OperatingSystemRootItemProvider operatingSystemRootItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.OperatingSystemRoot}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createOperatingSystemRootAdapter() {
		if (operatingSystemRootItemProvider == null) {
			operatingSystemRootItemProvider = new OperatingSystemRootItemProvider(this);
		}

		return operatingSystemRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.OperatingSystemUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected OperatingSystemUnitItemProvider operatingSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.OperatingSystemUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createOperatingSystemUnitAdapter() {
		if (operatingSystemUnitItemProvider == null) {
			operatingSystemUnitItemProvider = new OperatingSystemUnitItemProvider(this);
		}

		return operatingSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.Port} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected PortItemProvider portItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.Port}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPortAdapter() {
		if (portItemProvider == null) {
			portItemProvider = new PortItemProvider(this);
		}

		return portItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.PortConfigUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected PortConfigUnitItemProvider portConfigUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.PortConfigUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createPortConfigUnitAdapter() {
		if (portConfigUnitItemProvider == null) {
			portConfigUnitItemProvider = new PortConfigUnitItemProvider(this);
		}

		return portConfigUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.PortConsumer} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected PortConsumerItemProvider portConsumerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.PortConsumer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createPortConsumerAdapter() {
		if (portConsumerItemProvider == null) {
			portConsumerItemProvider = new PortConsumerItemProvider(this);
		}

		return portConsumerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.RedhatLinuxLocalGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RedhatLinuxLocalGroupItemProvider redhatLinuxLocalGroupItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.RedhatLinuxLocalGroup}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createRedhatLinuxLocalGroupAdapter() {
		if (redhatLinuxLocalGroupItemProvider == null) {
			redhatLinuxLocalGroupItemProvider = new RedhatLinuxLocalGroupItemProvider(this);
		}

		return redhatLinuxLocalGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.RedhatLinuxLocalService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RedhatLinuxLocalServiceItemProvider redhatLinuxLocalServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.RedhatLinuxLocalService}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createRedhatLinuxLocalServiceAdapter() {
		if (redhatLinuxLocalServiceItemProvider == null) {
			redhatLinuxLocalServiceItemProvider = new RedhatLinuxLocalServiceItemProvider(this);
		}

		return redhatLinuxLocalServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.RedhatLinuxLocalUser} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected RedhatLinuxLocalUserItemProvider redhatLinuxLocalUserItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.RedhatLinuxLocalUser}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createRedhatLinuxLocalUserAdapter() {
		if (redhatLinuxLocalUserItemProvider == null) {
			redhatLinuxLocalUserItemProvider = new RedhatLinuxLocalUserItemProvider(this);
		}

		return redhatLinuxLocalUserItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.RedhatLinuxOperatingSystem} instances.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	protected RedhatLinuxOperatingSystemItemProvider redhatLinuxOperatingSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.RedhatLinuxOperatingSystem}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRedhatLinuxOperatingSystemAdapter() {
		if (redhatLinuxOperatingSystemItemProvider == null) {
			redhatLinuxOperatingSystemItemProvider = new RedhatLinuxOperatingSystemItemProvider(this);
		}

		return redhatLinuxOperatingSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.RemoteFileSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RemoteFileSystemItemProvider remoteFileSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.RemoteFileSystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRemoteFileSystemAdapter() {
		if (remoteFileSystemItemProvider == null) {
			remoteFileSystemItemProvider = new RemoteFileSystemItemProvider(this);
		}

		return remoteFileSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.RemoteFileSystemUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RemoteFileSystemUnitItemProvider remoteFileSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.RemoteFileSystemUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRemoteFileSystemUnitAdapter() {
		if (remoteFileSystemUnitItemProvider == null) {
			remoteFileSystemUnitItemProvider = new RemoteFileSystemUnitItemProvider(this);
		}

		return remoteFileSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.SMBFileSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SMBFileSystemItemProvider smbFileSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.SMBFileSystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSMBFileSystemAdapter() {
		if (smbFileSystemItemProvider == null) {
			smbFileSystemItemProvider = new SMBFileSystemItemProvider(this);
		}

		return smbFileSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.SMBFileSystemUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SMBFileSystemUnitItemProvider smbFileSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.SMBFileSystemUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSMBFileSystemUnitAdapter() {
		if (smbFileSystemUnitItemProvider == null) {
			smbFileSystemUnitItemProvider = new SMBFileSystemUnitItemProvider(this);
		}

		return smbFileSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.SolarisFileSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SolarisFileSystemItemProvider solarisFileSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.SolarisFileSystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSolarisFileSystemAdapter() {
		if (solarisFileSystemItemProvider == null) {
			solarisFileSystemItemProvider = new SolarisFileSystemItemProvider(this);
		}

		return solarisFileSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.SolarisFileSystemUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SolarisFileSystemUnitItemProvider solarisFileSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.SolarisFileSystemUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSolarisFileSystemUnitAdapter() {
		if (solarisFileSystemUnitItemProvider == null) {
			solarisFileSystemUnitItemProvider = new SolarisFileSystemUnitItemProvider(this);
		}

		return solarisFileSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.SUSELinuxLocalGroup} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected SUSELinuxLocalGroupItemProvider suseLinuxLocalGroupItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.SUSELinuxLocalGroup}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createSUSELinuxLocalGroupAdapter() {
		if (suseLinuxLocalGroupItemProvider == null) {
			suseLinuxLocalGroupItemProvider = new SUSELinuxLocalGroupItemProvider(this);
		}

		return suseLinuxLocalGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.SUSELinuxLocalService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SUSELinuxLocalServiceItemProvider suseLinuxLocalServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.SUSELinuxLocalService}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createSUSELinuxLocalServiceAdapter() {
		if (suseLinuxLocalServiceItemProvider == null) {
			suseLinuxLocalServiceItemProvider = new SUSELinuxLocalServiceItemProvider(this);
		}

		return suseLinuxLocalServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.SUSELinuxLocalUser} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected SUSELinuxLocalUserItemProvider suseLinuxLocalUserItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.SUSELinuxLocalUser}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createSUSELinuxLocalUserAdapter() {
		if (suseLinuxLocalUserItemProvider == null) {
			suseLinuxLocalUserItemProvider = new SUSELinuxLocalUserItemProvider(this);
		}

		return suseLinuxLocalUserItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.SUSELinuxOperatingSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SUSELinuxOperatingSystemItemProvider suseLinuxOperatingSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.SUSELinuxOperatingSystem}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSUSELinuxOperatingSystemAdapter() {
		if (suseLinuxOperatingSystemItemProvider == null) {
			suseLinuxOperatingSystemItemProvider = new SUSELinuxOperatingSystemItemProvider(this);
		}

		return suseLinuxOperatingSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.UnixDirectory} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected UnixDirectoryItemProvider unixDirectoryItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.UnixDirectory}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createUnixDirectoryAdapter() {
		if (unixDirectoryItemProvider == null) {
			unixDirectoryItemProvider = new UnixDirectoryItemProvider(this);
		}

		return unixDirectoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.UnixFileSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnixFileSystemItemProvider unixFileSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.UnixFileSystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUnixFileSystemAdapter() {
		if (unixFileSystemItemProvider == null) {
			unixFileSystemItemProvider = new UnixFileSystemItemProvider(this);
		}

		return unixFileSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.UnixFileSystemUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnixFileSystemUnitItemProvider unixFileSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.UnixFileSystemUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUnixFileSystemUnitAdapter() {
		if (unixFileSystemUnitItemProvider == null) {
			unixFileSystemUnitItemProvider = new UnixFileSystemUnitItemProvider(this);
		}

		return unixFileSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.User} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected UserItemProvider userItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.User}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUserAdapter() {
		if (userItemProvider == null) {
			userItemProvider = new UserItemProvider(this);
		}

		return userItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.UserGroup} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected UserGroupItemProvider userGroupItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.UserGroup}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createUserGroupAdapter() {
		if (userGroupItemProvider == null) {
			userGroupItemProvider = new UserGroupItemProvider(this);
		}

		return userGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.UserGroupUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected UserGroupUnitItemProvider userGroupUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.UserGroupUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createUserGroupUnitAdapter() {
		if (userGroupUnitItemProvider == null) {
			userGroupUnitItemProvider = new UserGroupUnitItemProvider(this);
		}

		return userGroupUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.UserUnit} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected UserUnitItemProvider userUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.UserUnit}.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUserUnitAdapter() {
		if (userUnitItemProvider == null) {
			userUnitItemProvider = new UserUnitItemProvider(this);
		}

		return userUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.WindowsDirectory} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WindowsDirectoryItemProvider windowsDirectoryItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.WindowsDirectory}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWindowsDirectoryAdapter() {
		if (windowsDirectoryItemProvider == null) {
			windowsDirectoryItemProvider = new WindowsDirectoryItemProvider(this);
		}

		return windowsDirectoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.WindowsFileSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WindowsFileSystemItemProvider windowsFileSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.WindowsFileSystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWindowsFileSystemAdapter() {
		if (windowsFileSystemItemProvider == null) {
			windowsFileSystemItemProvider = new WindowsFileSystemItemProvider(this);
		}

		return windowsFileSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.WindowsFileSystemUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WindowsFileSystemUnitItemProvider windowsFileSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.WindowsFileSystemUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWindowsFileSystemUnitAdapter() {
		if (windowsFileSystemUnitItemProvider == null) {
			windowsFileSystemUnitItemProvider = new WindowsFileSystemUnitItemProvider(this);
		}

		return windowsFileSystemUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.WindowsLocalGroup} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WindowsLocalGroupItemProvider windowsLocalGroupItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.WindowsLocalGroup}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWindowsLocalGroupAdapter() {
		if (windowsLocalGroupItemProvider == null) {
			windowsLocalGroupItemProvider = new WindowsLocalGroupItemProvider(this);
		}

		return windowsLocalGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.WindowsLocalGroupUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WindowsLocalGroupUnitItemProvider windowsLocalGroupUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.WindowsLocalGroupUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWindowsLocalGroupUnitAdapter() {
		if (windowsLocalGroupUnitItemProvider == null) {
			windowsLocalGroupUnitItemProvider = new WindowsLocalGroupUnitItemProvider(this);
		}

		return windowsLocalGroupUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.WindowsLocalService} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WindowsLocalServiceItemProvider windowsLocalServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.WindowsLocalService}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWindowsLocalServiceAdapter() {
		if (windowsLocalServiceItemProvider == null) {
			windowsLocalServiceItemProvider = new WindowsLocalServiceItemProvider(this);
		}

		return windowsLocalServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.WindowsLocalServiceUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WindowsLocalServiceUnitItemProvider windowsLocalServiceUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.WindowsLocalServiceUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWindowsLocalServiceUnitAdapter() {
		if (windowsLocalServiceUnitItemProvider == null) {
			windowsLocalServiceUnitItemProvider = new WindowsLocalServiceUnitItemProvider(this);
		}

		return windowsLocalServiceUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.WindowsLocalUser} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WindowsLocalUserItemProvider windowsLocalUserItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.WindowsLocalUser}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWindowsLocalUserAdapter() {
		if (windowsLocalUserItemProvider == null) {
			windowsLocalUserItemProvider = new WindowsLocalUserItemProvider(this);
		}

		return windowsLocalUserItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.WindowsLocalUserUnit} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WindowsLocalUserUnitItemProvider windowsLocalUserUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.WindowsLocalUserUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWindowsLocalUserUnitAdapter() {
		if (windowsLocalUserUnitItemProvider == null) {
			windowsLocalUserUnitItemProvider = new WindowsLocalUserUnitItemProvider(this);
		}

		return windowsLocalUserUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.WindowsOperatingSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WindowsOperatingSystemItemProvider windowsOperatingSystemItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.WindowsOperatingSystem}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWindowsOperatingSystemAdapter() {
		if (windowsOperatingSystemItemProvider == null) {
			windowsOperatingSystemItemProvider = new WindowsOperatingSystemItemProvider(this);
		}

		return windowsOperatingSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.os.WindowsOperatingSystemUnit} instances.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WindowsOperatingSystemUnitItemProvider windowsOperatingSystemUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.os.WindowsOperatingSystemUnit}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWindowsOperatingSystemUnitAdapter() {
		if (windowsOperatingSystemUnitItemProvider == null) {
			windowsOperatingSystemUnitItemProvider = new WindowsOperatingSystemUnitItemProvider(this);
		}

		return windowsOperatingSystemUnitItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class) || (((Class) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (aixLocalGroupItemProvider != null)
			aixLocalGroupItemProvider.dispose();
		if (aixLocalGroupUnitItemProvider != null)
			aixLocalGroupUnitItemProvider.dispose();
		if (aixLocalServiceItemProvider != null)
			aixLocalServiceItemProvider.dispose();
		if (aixLocalServiceUnitItemProvider != null)
			aixLocalServiceUnitItemProvider.dispose();
		if (aixLocalUserItemProvider != null)
			aixLocalUserItemProvider.dispose();
		if (aixLocalUserUnitItemProvider != null)
			aixLocalUserUnitItemProvider.dispose();
		if (aixOperatingSystemItemProvider != null)
			aixOperatingSystemItemProvider.dispose();
		if (aixOperatingSystemUnitItemProvider != null)
			aixOperatingSystemUnitItemProvider.dispose();
		if (dataFileItemProvider != null)
			dataFileItemProvider.dispose();
		if (dataFileUnitItemProvider != null)
			dataFileUnitItemProvider.dispose();
		if (directoryItemProvider != null)
			directoryItemProvider.dispose();
		if (directoryUnitItemProvider != null)
			directoryUnitItemProvider.dispose();
		if (fileSystemItemProvider != null)
			fileSystemItemProvider.dispose();
		if (fileSystemContentItemProvider != null)
			fileSystemContentItemProvider.dispose();
		if (fileSystemContentUnitItemProvider != null)
			fileSystemContentUnitItemProvider.dispose();
		if (fileSystemUnitItemProvider != null)
			fileSystemUnitItemProvider.dispose();
		if (linuxLocalGroupItemProvider != null)
			linuxLocalGroupItemProvider.dispose();
		if (linuxLocalGroupUnitItemProvider != null)
			linuxLocalGroupUnitItemProvider.dispose();
		if (linuxLocalServiceItemProvider != null)
			linuxLocalServiceItemProvider.dispose();
		if (linuxLocalServiceUnitItemProvider != null)
			linuxLocalServiceUnitItemProvider.dispose();
		if (linuxLocalUserItemProvider != null)
			linuxLocalUserItemProvider.dispose();
		if (linuxLocalUserUnitItemProvider != null)
			linuxLocalUserUnitItemProvider.dispose();
		if (linuxOperatingSystemItemProvider != null)
			linuxOperatingSystemItemProvider.dispose();
		if (linuxOperatingSystemUnitItemProvider != null)
			linuxOperatingSystemUnitItemProvider.dispose();
		if (localFileSystemItemProvider != null)
			localFileSystemItemProvider.dispose();
		if (localFileSystemUnitItemProvider != null)
			localFileSystemUnitItemProvider.dispose();
		if (nfsFileSystemItemProvider != null)
			nfsFileSystemItemProvider.dispose();
		if (nfsFileSystemUnitItemProvider != null)
			nfsFileSystemUnitItemProvider.dispose();
		if (openVmsFileSystemItemProvider != null)
			openVmsFileSystemItemProvider.dispose();
		if (openVmsFileSystemUnitItemProvider != null)
			openVmsFileSystemUnitItemProvider.dispose();
		if (operatingSystemItemProvider != null)
			operatingSystemItemProvider.dispose();
		if (operatingSystemRootItemProvider != null)
			operatingSystemRootItemProvider.dispose();
		if (operatingSystemUnitItemProvider != null)
			operatingSystemUnitItemProvider.dispose();
		if (portItemProvider != null)
			portItemProvider.dispose();
		if (portConfigUnitItemProvider != null)
			portConfigUnitItemProvider.dispose();
		if (portConsumerItemProvider != null)
			portConsumerItemProvider.dispose();
		if (redhatLinuxLocalGroupItemProvider != null)
			redhatLinuxLocalGroupItemProvider.dispose();
		if (redhatLinuxLocalServiceItemProvider != null)
			redhatLinuxLocalServiceItemProvider.dispose();
		if (redhatLinuxLocalUserItemProvider != null)
			redhatLinuxLocalUserItemProvider.dispose();
		if (redhatLinuxOperatingSystemItemProvider != null)
			redhatLinuxOperatingSystemItemProvider.dispose();
		if (remoteFileSystemItemProvider != null)
			remoteFileSystemItemProvider.dispose();
		if (remoteFileSystemUnitItemProvider != null)
			remoteFileSystemUnitItemProvider.dispose();
		if (smbFileSystemItemProvider != null)
			smbFileSystemItemProvider.dispose();
		if (smbFileSystemUnitItemProvider != null)
			smbFileSystemUnitItemProvider.dispose();
		if (solarisFileSystemItemProvider != null)
			solarisFileSystemItemProvider.dispose();
		if (solarisFileSystemUnitItemProvider != null)
			solarisFileSystemUnitItemProvider.dispose();
		if (suseLinuxLocalGroupItemProvider != null)
			suseLinuxLocalGroupItemProvider.dispose();
		if (suseLinuxLocalServiceItemProvider != null)
			suseLinuxLocalServiceItemProvider.dispose();
		if (suseLinuxLocalUserItemProvider != null)
			suseLinuxLocalUserItemProvider.dispose();
		if (suseLinuxOperatingSystemItemProvider != null)
			suseLinuxOperatingSystemItemProvider.dispose();
		if (unixDirectoryItemProvider != null)
			unixDirectoryItemProvider.dispose();
		if (unixFileSystemItemProvider != null)
			unixFileSystemItemProvider.dispose();
		if (unixFileSystemUnitItemProvider != null)
			unixFileSystemUnitItemProvider.dispose();
		if (userItemProvider != null)
			userItemProvider.dispose();
		if (userGroupItemProvider != null)
			userGroupItemProvider.dispose();
		if (userGroupUnitItemProvider != null)
			userGroupUnitItemProvider.dispose();
		if (userUnitItemProvider != null)
			userUnitItemProvider.dispose();
		if (windowsDirectoryItemProvider != null)
			windowsDirectoryItemProvider.dispose();
		if (windowsFileSystemItemProvider != null)
			windowsFileSystemItemProvider.dispose();
		if (windowsFileSystemUnitItemProvider != null)
			windowsFileSystemUnitItemProvider.dispose();
		if (windowsLocalGroupItemProvider != null)
			windowsLocalGroupItemProvider.dispose();
		if (windowsLocalGroupUnitItemProvider != null)
			windowsLocalGroupUnitItemProvider.dispose();
		if (windowsLocalServiceItemProvider != null)
			windowsLocalServiceItemProvider.dispose();
		if (windowsLocalServiceUnitItemProvider != null)
			windowsLocalServiceUnitItemProvider.dispose();
		if (windowsLocalUserItemProvider != null)
			windowsLocalUserItemProvider.dispose();
		if (windowsLocalUserUnitItemProvider != null)
			windowsLocalUserUnitItemProvider.dispose();
		if (windowsOperatingSystemItemProvider != null)
			windowsOperatingSystemItemProvider.dispose();
		if (windowsOperatingSystemUnitItemProvider != null)
			windowsOperatingSystemUnitItemProvider.dispose();
	}

}
