/**
 * <copyright>
 * </copyright>
 *
 * $Id: ServerRootValidator.java,v 1.5 2008/02/01 23:00:15 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.server.validation;

import java.util.Map;

import org.eclipse.emf.ecore.util.FeatureMap;

import com.ibm.ccl.soa.deploy.server.Server;
import com.ibm.ccl.soa.deploy.server.ServerUnit;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.server.ServerRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServerRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);

	boolean validateXMLNSPrefixMap(Map value);

	boolean validateXSISchemaLocation(Map value);

	boolean validateCapabilityServer(Server value);

	boolean validateUnitServerUnit(ServerUnit value);
}
