/**
 * <copyright>
 * </copyright>
 *
 * $Id: GenericsoftwareRootValidator.java,v 1.2 2008/02/05 22:20:21 chadh Exp $
 */
package com.ibm.ccl.soa.deploy.genericsoftware.validation;

import org.eclipse.emf.common.util.EMap;
import org.eclipse.emf.ecore.util.FeatureMap;

import com.ibm.ccl.soa.deploy.genericsoftware.SoftwareInstall;
import com.ibm.ccl.soa.deploy.genericsoftware.SoftwareInstallUnit;
import com.ibm.ccl.soa.deploy.genericsoftware.SoftwarePatch;
import com.ibm.ccl.soa.deploy.genericsoftware.SoftwarePatchUnit;
import com.ibm.ccl.soa.deploy.genericsoftware.Version;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.genericsoftware.GenericsoftwareRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GenericsoftwareRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateXMLNSPrefixMap(EMap value);
	boolean validateXSISchemaLocation(EMap value);
	boolean validateCapabilitySoftwareInstall(SoftwareInstall value);
	boolean validateCapabilitySoftwarePatch(SoftwarePatch value);
	boolean validateCapabilityVersion(Version value);
	boolean validateUnitSoftwareInstallUnit(SoftwareInstallUnit value);
	boolean validateUnitSoftwarePatchUnit(SoftwarePatchUnit value);
}
