/**
 * <copyright>
 * </copyright>
 *
 * $Id: SoftwareInstallUnitValidator.java,v 1.1 2008/02/04 15:55:28 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.genericsoftware.validation;


/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.genericsoftware.SoftwareInstallUnit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SoftwareInstallUnitValidator {
	boolean validate();

}
