<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ContractRefactoringChangesDataModels"
    nsURI="http://www.ibm.com/soa/deploy/ide/refactoring/changes/contracts/1.0">
  <eAnnotations source="http://www.eclipse.org/webtools/datamodels">
    <details key="apiPackage" value="com.ibm.ccl.soa.deploy.ide.refactoring.changes"/>
    <details key="internalPackage" value="com.ibm.ccl.soa.deploy.ide.internal.refactoring.datamodels"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyContractChange" eSuperTypes="refactoring-changes.ecore#//RefactoringDataModelChange">
    <eAnnotations source="http://www.eclipse.org/webtools/datamodels">
      <details key="documentation" value="Modify the Contract of the selected Topology."/>
      <details key="providerBaseType"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType refactoring.ecore#//IPath">
      <eAnnotations source="http://www.eclipse.org/webtools/datamodels">
        <details key="documentation" value=""/>
        <details key="required" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newContractType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/webtools/datamodels">
        <details key="documentation" value=" The id of the new contract type. See {@link ContractProviderManager} for more information"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
