/*******************************************************************************
 * Copyright (c) 2003, 2007 IBM Corporation Licensed Material - Property of IBM. All rights reserved.
 *  
 * US Government Users Restricted Rights - Use, duplication or disclosure v1.0 restricted by GSA ADP
 * Schedule Contract with IBM Corp.
 * 
 * Contributors: IBM Corporation - initial API and implementation
 *******************************************************************************/
package com.ibm.ccl.soa.deploy.core.validation;

import java.util.List;

import org.eclipse.emf.ecore.util.FeatureMap;

import com.ibm.ccl.soa.deploy.core.ConfigurationContract;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.core.Topology}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TopologyValidator {
	boolean validate();

	boolean validateUnitGroup(FeatureMap value);

	boolean validateUnits(List value);

	boolean validateUnitLinksGroup(FeatureMap value);

	boolean validateUnitLinks(List value);

	boolean validateConstraintLinks(List value);

	boolean validateDependencyLinkGroup(FeatureMap value);

	boolean validateDependencyLinks(List value);

	boolean validateRealizationLinks(List value);

	boolean validateImports(List value);

	boolean validateConfigurationContractGroup(FeatureMap value);

	boolean validateConfigurationContract(ConfigurationContract value);

	boolean validateDecoratorSemantic(String value);

	boolean validateNamespace(String value);
}
