/*******************************************************************************
 * Copyright (c) 2003, 2007 IBM Corporation Licensed Material - Property of IBM. All rights reserved.
 *  
 * US Government Users Restricted Rights - Use, duplication or disclosure v1.0 restricted by GSA ADP
 * Schedule Contract with IBM Corp.
 * 
 * Contributors: IBM Corporation - initial API and implementation
 *******************************************************************************/
package com.ibm.ccl.soa.deploy.j2ee.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import com.ibm.ccl.soa.deploy.j2ee.util.J2eeAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc --> <!--
 * end-user-doc -->
 * @generated
 */
public class J2eeItemProviderAdapterFactory extends J2eeAdapterFactory implements
		ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public static final String copyright = "Copyright (c) 2005, 2006 IBM Corporation. Licensed Material - Property of IBM. All rights reserved."; //$NON-NLS-1$

	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection supportedTypes = new ArrayList();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public J2eeItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.AppClient} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected AppClientItemProvider appClientItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.AppClient}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createAppClientAdapter() {
		if (appClientItemProvider == null) {
			appClientItemProvider = new AppClientItemProvider(this);
		}

		return appClientItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.AppClientModule} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected AppClientModuleItemProvider appClientModuleItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.AppClientModule}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createAppClientModuleAdapter() {
		if (appClientModuleItemProvider == null) {
			appClientModuleItemProvider = new AppClientModuleItemProvider(this);
		}

		return appClientModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.EarModule} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected EarModuleItemProvider earModuleItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.EarModule}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createEarModuleAdapter() {
		if (earModuleItemProvider == null) {
			earModuleItemProvider = new EarModuleItemProvider(this);
		}

		return earModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.EARModuleCapability} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EARModuleCapabilityItemProvider earModuleCapabilityItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.EARModuleCapability}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createEARModuleCapabilityAdapter() {
		if (earModuleCapabilityItemProvider == null) {
			earModuleCapabilityItemProvider = new EARModuleCapabilityItemProvider(this);
		}

		return earModuleCapabilityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.EJB} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected EJBItemProvider ejbItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.EJB}.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEJBAdapter() {
		if (ejbItemProvider == null) {
			ejbItemProvider = new EJBItemProvider(this);
		}

		return ejbItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.EJBContainer} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected EJBContainerItemProvider ejbContainerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.EJBContainer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createEJBContainerAdapter() {
		if (ejbContainerItemProvider == null) {
			ejbContainerItemProvider = new EJBContainerItemProvider(this);
		}

		return ejbContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.EjbModule} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected EjbModuleItemProvider ejbModuleItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.EjbModule}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createEjbModuleAdapter() {
		if (ejbModuleItemProvider == null) {
			ejbModuleItemProvider = new EjbModuleItemProvider(this);
		}

		return ejbModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.EJBModuleCapability} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EJBModuleCapabilityItemProvider ejbModuleCapabilityItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.EJBModuleCapability}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createEJBModuleCapabilityAdapter() {
		if (ejbModuleCapabilityItemProvider == null) {
			ejbModuleCapabilityItemProvider = new EJBModuleCapabilityItemProvider(this);
		}

		return ejbModuleCapabilityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.EnterpriseBeanService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnterpriseBeanServiceItemProvider enterpriseBeanServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.EnterpriseBeanService}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createEnterpriseBeanServiceAdapter() {
		if (enterpriseBeanServiceItemProvider == null) {
			enterpriseBeanServiceItemProvider = new EnterpriseBeanServiceItemProvider(this);
		}

		return enterpriseBeanServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.EntityService} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected EntityServiceItemProvider entityServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.EntityService}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createEntityServiceAdapter() {
		if (entityServiceItemProvider == null) {
			entityServiceItemProvider = new EntityServiceItemProvider(this);
		}

		return entityServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.GenericJ2eeServer} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected GenericJ2eeServerItemProvider genericJ2eeServerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.GenericJ2eeServer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createGenericJ2eeServerAdapter() {
		if (genericJ2eeServerItemProvider == null) {
			genericJ2eeServerItemProvider = new GenericJ2eeServerItemProvider(this);
		}

		return genericJ2eeServerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.GenericWebServer} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected GenericWebServerItemProvider genericWebServerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.GenericWebServer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createGenericWebServerAdapter() {
		if (genericWebServerItemProvider == null) {
			genericWebServerItemProvider = new GenericWebServerItemProvider(this);
		}

		return genericWebServerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.J2CAuthenticationDataEntry} instances.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	protected J2CAuthenticationDataEntryItemProvider j2CAuthenticationDataEntryItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.J2CAuthenticationDataEntry}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createJ2CAuthenticationDataEntryAdapter() {
		if (j2CAuthenticationDataEntryItemProvider == null) {
			j2CAuthenticationDataEntryItemProvider = new J2CAuthenticationDataEntryItemProvider(this);
		}

		return j2CAuthenticationDataEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.J2EEContainer} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected J2EEContainerItemProvider j2EEContainerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.J2EEContainer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJ2EEContainerAdapter() {
		if (j2EEContainerItemProvider == null) {
			j2EEContainerItemProvider = new J2EEContainerItemProvider(this);
		}

		return j2EEContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.J2EEDatasource} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected J2EEDatasourceItemProvider j2EEDatasourceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.J2EEDatasource}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJ2EEDatasourceAdapter() {
		if (j2EEDatasourceItemProvider == null) {
			j2EEDatasourceItemProvider = new J2EEDatasourceItemProvider(this);
		}

		return j2EEDatasourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.J2EEDeployRoot} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected J2EEDeployRootItemProvider j2EEDeployRootItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.J2EEDeployRoot}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJ2EEDeployRootAdapter() {
		if (j2EEDeployRootItemProvider == null) {
			j2EEDeployRootItemProvider = new J2EEDeployRootItemProvider(this);
		}

		return j2EEDeployRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.J2EEModuleCapability} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected J2EEModuleCapabilityItemProvider j2EEModuleCapabilityItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.J2EEModuleCapability}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJ2EEModuleCapabilityAdapter() {
		if (j2EEModuleCapabilityItemProvider == null) {
			j2EEModuleCapabilityItemProvider = new J2EEModuleCapabilityItemProvider(this);
		}

		return j2EEModuleCapabilityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link com.ibm.ccl.soa.deploy.j2ee.J2EEResourceEnvironmentRequirement} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected J2EEResourceEnvironmentRequirementItemProvider j2EEResourceEnvironmentRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.J2EEResourceEnvironmentRequirement}.
	 * <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createJ2EEResourceEnvironmentRequirementAdapter() {
		if (j2EEResourceEnvironmentRequirementItemProvider == null) {
			j2EEResourceEnvironmentRequirementItemProvider = new J2EEResourceEnvironmentRequirementItemProvider(
					this);
		}

		return j2EEResourceEnvironmentRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.J2EEResourceRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected J2EEResourceRequirementItemProvider j2EEResourceRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.J2EEResourceRequirement}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createJ2EEResourceRequirementAdapter() {
		if (j2EEResourceRequirementItemProvider == null) {
			j2EEResourceRequirementItemProvider = new J2EEResourceRequirementItemProvider(this);
		}

		return j2EEResourceRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.J2EESecurityRole} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected J2EESecurityRoleItemProvider j2EESecurityRoleItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.J2EESecurityRole}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJ2EESecurityRoleAdapter() {
		if (j2EESecurityRoleItemProvider == null) {
			j2EESecurityRoleItemProvider = new J2EESecurityRoleItemProvider(this);
		}

		return j2EESecurityRoleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.J2EEServer} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected J2EEServerItemProvider j2EEServerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.J2EEServer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJ2EEServerAdapter() {
		if (j2EEServerItemProvider == null) {
			j2EEServerItemProvider = new J2EEServerItemProvider(this);
		}

		return j2EEServerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.J2EEServerUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected J2EEServerUnitItemProvider j2EEServerUnitItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.J2EEServerUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createJ2EEServerUnitAdapter() {
		if (j2EEServerUnitItemProvider == null) {
			j2EEServerUnitItemProvider = new J2EEServerUnitItemProvider(this);
		}

		return j2EEServerUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.JarModule} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected JarModuleItemProvider jarModuleItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.JarModule}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJarModuleAdapter() {
		if (jarModuleItemProvider == null) {
			jarModuleItemProvider = new JarModuleItemProvider(this);
		}

		return jarModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.JarModuleCapability} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JarModuleCapabilityItemProvider jarModuleCapabilityItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.JarModuleCapability}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJarModuleCapabilityAdapter() {
		if (jarModuleCapabilityItemProvider == null) {
			jarModuleCapabilityItemProvider = new JarModuleCapabilityItemProvider(this);
		}

		return jarModuleCapabilityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.JavaInterface} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected JavaInterfaceItemProvider javaInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.JavaInterface}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJavaInterfaceAdapter() {
		if (javaInterfaceItemProvider == null) {
			javaInterfaceItemProvider = new JavaInterfaceItemProvider(this);
		}

		return javaInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.JCAContainer} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected JCAContainerItemProvider jcaContainerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.JCAContainer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJCAContainerAdapter() {
		if (jcaContainerItemProvider == null) {
			jcaContainerItemProvider = new JCAContainerItemProvider(this);
		}

		return jcaContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.JCAModule} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected JCAModuleItemProvider jcaModuleItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.JCAModule}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJCAModuleAdapter() {
		if (jcaModuleItemProvider == null) {
			jcaModuleItemProvider = new JCAModuleItemProvider(this);
		}

		return jcaModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.JCAModuleCapability} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JCAModuleCapabilityItemProvider jcaModuleCapabilityItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.JCAModuleCapability}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJCAModuleCapabilityAdapter() {
		if (jcaModuleCapabilityItemProvider == null) {
			jcaModuleCapabilityItemProvider = new JCAModuleCapabilityItemProvider(this);
		}

		return jcaModuleCapabilityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.JSPContainer} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected JSPContainerItemProvider jspContainerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.JSPContainer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createJSPContainerAdapter() {
		if (jspContainerItemProvider == null) {
			jspContainerItemProvider = new JSPContainerItemProvider(this);
		}

		return jspContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.ServletContainer} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected ServletContainerItemProvider servletContainerItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.ServletContainer}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createServletContainerAdapter() {
		if (servletContainerItemProvider == null) {
			servletContainerItemProvider = new ServletContainerItemProvider(this);
		}

		return servletContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.SessionService} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected SessionServiceItemProvider sessionServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.SessionService}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createSessionServiceAdapter() {
		if (sessionServiceItemProvider == null) {
			sessionServiceItemProvider = new SessionServiceItemProvider(this);
		}

		return sessionServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.URLInterface} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected URLInterfaceItemProvider urlInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.URLInterface}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createURLInterfaceAdapter() {
		if (urlInterfaceItemProvider == null) {
			urlInterfaceItemProvider = new URLInterfaceItemProvider(this);
		}

		return urlInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.URLService} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected URLServiceItemProvider urlServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.URLService}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createURLServiceAdapter() {
		if (urlServiceItemProvider == null) {
			urlServiceItemProvider = new URLServiceItemProvider(this);
		}

		return urlServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.WebModule} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected WebModuleItemProvider webModuleItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.WebModule}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWebModuleAdapter() {
		if (webModuleItemProvider == null) {
			webModuleItemProvider = new WebModuleItemProvider(this);
		}

		return webModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.WebModuleCapability} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WebModuleCapabilityItemProvider webModuleCapabilityItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.WebModuleCapability}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWebModuleCapabilityAdapter() {
		if (webModuleCapabilityItemProvider == null) {
			webModuleCapabilityItemProvider = new WebModuleCapabilityItemProvider(this);
		}

		return webModuleCapabilityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.WebService} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WebServiceItemProvider webServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.WebService}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWebServiceAdapter() {
		if (webServiceItemProvider == null) {
			webServiceItemProvider = new WebServiceItemProvider(this);
		}

		return webServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.ibm.ccl.soa.deploy.j2ee.WSDLInterface} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected WSDLInterfaceItemProvider wsdlInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link com.ibm.ccl.soa.deploy.j2ee.WSDLInterface}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter createWSDLInterfaceAdapter() {
		if (wsdlInterfaceItemProvider == null) {
			wsdlInterfaceItemProvider = new WSDLInterfaceItemProvider(this);
		}

		return wsdlInterfaceItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class) || (((Class) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (appClientItemProvider != null)
			appClientItemProvider.dispose();
		if (appClientModuleItemProvider != null)
			appClientModuleItemProvider.dispose();
		if (earModuleItemProvider != null)
			earModuleItemProvider.dispose();
		if (earModuleCapabilityItemProvider != null)
			earModuleCapabilityItemProvider.dispose();
		if (ejbItemProvider != null)
			ejbItemProvider.dispose();
		if (ejbContainerItemProvider != null)
			ejbContainerItemProvider.dispose();
		if (ejbModuleItemProvider != null)
			ejbModuleItemProvider.dispose();
		if (ejbModuleCapabilityItemProvider != null)
			ejbModuleCapabilityItemProvider.dispose();
		if (enterpriseBeanServiceItemProvider != null)
			enterpriseBeanServiceItemProvider.dispose();
		if (entityServiceItemProvider != null)
			entityServiceItemProvider.dispose();
		if (genericJ2eeServerItemProvider != null)
			genericJ2eeServerItemProvider.dispose();
		if (genericWebServerItemProvider != null)
			genericWebServerItemProvider.dispose();
		if (j2CAuthenticationDataEntryItemProvider != null)
			j2CAuthenticationDataEntryItemProvider.dispose();
		if (j2EEContainerItemProvider != null)
			j2EEContainerItemProvider.dispose();
		if (j2EEDatasourceItemProvider != null)
			j2EEDatasourceItemProvider.dispose();
		if (j2EEDeployRootItemProvider != null)
			j2EEDeployRootItemProvider.dispose();
		if (j2EEModuleCapabilityItemProvider != null)
			j2EEModuleCapabilityItemProvider.dispose();
		if (j2EEResourceEnvironmentRequirementItemProvider != null)
			j2EEResourceEnvironmentRequirementItemProvider.dispose();
		if (j2EEResourceRequirementItemProvider != null)
			j2EEResourceRequirementItemProvider.dispose();
		if (j2EESecurityRoleItemProvider != null)
			j2EESecurityRoleItemProvider.dispose();
		if (j2EEServerItemProvider != null)
			j2EEServerItemProvider.dispose();
		if (j2EEServerUnitItemProvider != null)
			j2EEServerUnitItemProvider.dispose();
		if (jarModuleItemProvider != null)
			jarModuleItemProvider.dispose();
		if (jarModuleCapabilityItemProvider != null)
			jarModuleCapabilityItemProvider.dispose();
		if (javaInterfaceItemProvider != null)
			javaInterfaceItemProvider.dispose();
		if (jcaContainerItemProvider != null)
			jcaContainerItemProvider.dispose();
		if (jcaModuleItemProvider != null)
			jcaModuleItemProvider.dispose();
		if (jcaModuleCapabilityItemProvider != null)
			jcaModuleCapabilityItemProvider.dispose();
		if (jspContainerItemProvider != null)
			jspContainerItemProvider.dispose();
		if (servletContainerItemProvider != null)
			servletContainerItemProvider.dispose();
		if (sessionServiceItemProvider != null)
			sessionServiceItemProvider.dispose();
		if (urlInterfaceItemProvider != null)
			urlInterfaceItemProvider.dispose();
		if (urlServiceItemProvider != null)
			urlServiceItemProvider.dispose();
		if (webModuleItemProvider != null)
			webModuleItemProvider.dispose();
		if (webModuleCapabilityItemProvider != null)
			webModuleCapabilityItemProvider.dispose();
		if (webServiceItemProvider != null)
			webServiceItemProvider.dispose();
		if (wsdlInterfaceItemProvider != null)
			wsdlInterfaceItemProvider.dispose();
	}

}
