/**
 * <copyright>
 * </copyright>
 *
 * $Id: IpInterfaceValidator.java,v 1.4 2008/02/06 02:37:53 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.net.validation;

import com.ibm.ccl.soa.deploy.net.IPv6AddressNotationType;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.net.IpInterface}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IpInterfaceValidator {
	boolean validate();

	boolean validateIpV4Address(String value);

	boolean validateIpV6Address(String value);

	boolean validateIpv6NotationType(IPv6AddressNotationType value);

	boolean validateL2InterfaceName(String value);

	boolean validateNetmask(String value);
	boolean validateSubnetAddress(String value);
}
