/**
 * <copyright>
 * </copyright>
 *
 * $Id: L2InterfaceValidator.java,v 1.1 2008/02/01 18:53:29 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.net.validation;

import com.ibm.ccl.soa.deploy.net.DuplexType;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.net.L2Interface}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface L2InterfaceValidator {
	boolean validate();

	boolean validateAutoNegotiation(boolean value);
	boolean validateBroadcast(boolean value);
	boolean validateDuplex(DuplexType value);
	boolean validateEncapsulation(String value);
	boolean validateHwAddress(String value);
	boolean validateIndex(int value);
	boolean validateL2InterfaceName(String value);
	boolean validateLoopback(boolean value);
	boolean validateMtu(int value);
	boolean validatePrivate(boolean value);
	boolean validatePromiscuous(boolean value);
	boolean validateSpeed(long value);
}
