/**
 * <copyright>
 * </copyright>
 *
 * $Id: L2InterfaceUnitValidator.java,v 1.1 2008/02/01 18:53:29 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.net.validation;


/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.net.L2InterfaceUnit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface L2InterfaceUnitValidator {
	boolean validate();

}
