/**
 * <copyright>
 * </copyright>
 *
 * $Id: AIXLocalServiceValidator.java,v 1.4 2007/12/19 23:37:05 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.os.validation;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.os.AIXLocalService}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AIXLocalServiceValidator {
	boolean validate();

	boolean validateActionType(String value);

	boolean validateExecutablePath(String value);

	boolean validateServiceDescription(String value);

	boolean validateStartupRunLevelEight(boolean value);

	boolean validateStartupRunLevelFive(boolean value);

	boolean validateStartupRunLevelFour(boolean value);

	boolean validateStartupRunLevelNine(boolean value);

	boolean validateStartupRunLevelOne(boolean value);

	boolean validateStartupRunLevelSeven(boolean value);

	boolean validateStartupRunLevelSix(boolean value);

	boolean validateStartupRunLevelThree(boolean value);

	boolean validateStartupRunLevelTwo(boolean value);

	boolean validateStartupRunLevelZero(boolean value);
}
