/**
 * <copyright>
 * </copyright>
 *
 * $Id: FileSystemContentValidator.java,v 1.1 2007/12/19 23:37:05 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.os.validation;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.os.FileSystemContent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FileSystemContentValidator {
	boolean validate();

	boolean validateFixedPath(String value);

	boolean validateGroup(String value);

	boolean validateLastModified(long value);

	boolean validateOwner(String value);

	boolean validatePermissions(String value);

	boolean validateRealFile(String value);

	boolean validateSize(long value);

	boolean validateURI(String value);
}
