/**
 * <copyright>
 * </copyright>
 *
 * $Id: LinuxLocalUserValidator.java,v 1.4 2007/12/19 23:37:05 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.os.validation;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.os.LinuxLocalUser}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LinuxLocalUserValidator {
	boolean validate();

	boolean validateAccountDescription(String value);

	boolean validateAccountDisabled(boolean value);

	boolean validateChangePasswordNextLogon(boolean value);

	boolean validateFullName(String value);

	boolean validateHomeDir(String value);

	boolean validatePasswordNeverExpires(boolean value);

	boolean validateShell(String value);

	boolean validateUserCannotChangePassword(boolean value);

	boolean validateUserName(String value);
}
