/**
 * <copyright>
 * </copyright>
 *
 * $Id: LinuxLocalServiceValidator.java,v 1.4 2007/12/19 23:37:05 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.os.validation;

import com.ibm.ccl.soa.deploy.os.LinuxServiceStartupTypeType;
import com.ibm.ccl.soa.deploy.os.LinuxServiceStatusType;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.os.LinuxLocalService}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LinuxLocalServiceValidator {
	boolean validate();

	boolean validateExecutablePath(String value);

	boolean validateServiceAccount(String value);

	boolean validateServiceDescription(String value);

	boolean validateServiceName(String value);

	boolean validateServiceStatus(LinuxServiceStatusType value);

	boolean validateStartupRunLevelFive(boolean value);

	boolean validateStartupRunLevelFour(boolean value);

	boolean validateStartupRunLevelOne(boolean value);

	boolean validateStartupRunLevelSix(boolean value);

	boolean validateStartupRunLevelThree(boolean value);

	boolean validateStartupRunLevelTwo(boolean value);

	boolean validateStartupRunLevelZero(boolean value);

	boolean validateStartupType(LinuxServiceStartupTypeType value);
}
