/**
 * <copyright>
 * </copyright>
 *
 * $Id: OperatingSystemValidator.java,v 1.6 2008/02/05 03:16:22 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.os.validation;

import com.ibm.ccl.soa.deploy.os.ArchitectureBusType;
import com.ibm.ccl.soa.deploy.os.KernelWidthType;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.os.OperatingSystem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperatingSystemValidator {
	boolean validate();

	boolean validateArchitectureBus(ArchitectureBusType value);

	boolean validateFqdn(String value);

	boolean validateHostname(String value);

	boolean validateKernelArchitecture(String value);

	boolean validateKernelVersion(String value);

	boolean validateKernelWidth(KernelWidthType value);

	boolean validateLocale(String value);

	boolean validateManufacturer(String value);

	boolean validateOsDistribution(String value);

	boolean validateOsServicepack(String value);

	boolean validateOsType(String value);

	boolean validateOsVersion(String value);

	boolean validateTimeZone(String value);
}
