/**
 * <copyright>
 * </copyright>
 *
 * $Id: RedhatLinuxOperatingSystemValidator.java,v 1.4 2007/12/19 23:37:05 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.os.validation;

import com.ibm.ccl.soa.deploy.os.RedhatDesktopType;
import com.ibm.ccl.soa.deploy.os.RedhatLinuxBootLoaderType;
import com.ibm.ccl.soa.deploy.os.RedhatLinuxProductTypeType;
import com.ibm.ccl.soa.deploy.os.SELinuxStateType;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.os.RedhatLinuxOperatingSystem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RedhatLinuxOperatingSystemValidator {
	boolean validate();

	boolean validateBootLoader(RedhatLinuxBootLoaderType value);

	boolean validateDesktop(RedhatDesktopType value);

	boolean validateInstallDate(String value);

	boolean validateLastBootUpTime(String value);

	boolean validateOwner(String value);

	boolean validateProductType(RedhatLinuxProductTypeType value);

	boolean validateSELinuxState(SELinuxStateType value);
}
