/**
 * <copyright>
 * </copyright>
 *
 * $Id: SUSELinuxOperatingSystemValidator.java,v 1.4 2007/12/19 23:37:05 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.os.validation;

import com.ibm.ccl.soa.deploy.os.SUSEDesktopType;
import com.ibm.ccl.soa.deploy.os.SUSELinuxBootLoaderType;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.os.SUSELinuxOperatingSystem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SUSELinuxOperatingSystemValidator {
	boolean validate();

	boolean validateBootLoader(SUSELinuxBootLoaderType value);

	boolean validateDesktop(SUSEDesktopType value);

	boolean validateLastBootUpDate(String value);
}
