/**
 * <copyright>
 * </copyright>
 *
 * $Id: WindowsOperatingSystemValidator.java,v 1.4 2007/12/19 23:37:05 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.os.validation;

import com.ibm.ccl.soa.deploy.os.EncryptionLevelType;
import com.ibm.ccl.soa.deploy.os.WindowsDirectoryType;
import com.ibm.ccl.soa.deploy.os.WindowsProductTypeType;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.os.WindowsOperatingSystem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WindowsOperatingSystemValidator {
	boolean validate();

	boolean validateCompany(String value);

	boolean validateDomainAdmin(String value);

	boolean validateDomainName(String value);

	boolean validateDomainPassword(String value);

	boolean validateEncryptionLevel(EncryptionLevelType value);

	boolean validateInstallDate(String value);

	boolean validateLanguage(String value);

	boolean validateLanguageGroup(String value);

	boolean validateLastBootUpTime(String value);

	boolean validateMachineObjectOU(String value);

	boolean validateNumberOfLicensedUsers(String value);

	boolean validateOwner(String value);

	boolean validateProductKey(String value);

	boolean validateProductType(WindowsProductTypeType value);

	boolean validateSystemDrive(String value);

	boolean validateTimeZone(String value);

	boolean validateWindowsDirectory(WindowsDirectoryType value);

	boolean validateWorkgroupName(String value);
}
