/**
 * <copyright>
 * </copyright>
 *
 * $Id: WindowsLocalServiceValidator.java,v 1.4 2007/12/19 23:37:05 barnold Exp $
 */
package com.ibm.ccl.soa.deploy.os.validation;

import com.ibm.ccl.soa.deploy.os.WindowsServiceErrorControlType;
import com.ibm.ccl.soa.deploy.os.WindowsServiceStartupType;
import com.ibm.ccl.soa.deploy.os.WindowsServiceStatusType;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.os.WindowsLocalService}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WindowsLocalServiceValidator {
	boolean validate();

	boolean validateDependantComponents(String value);

	boolean validateErrorControl(WindowsServiceErrorControlType value);

	boolean validateExecutablePath(String value);

	boolean validateLogOnAsSystem(boolean value);

	boolean validateRunProgram(String value);

	boolean validateServiceAccount(String value);

	boolean validateServiceAccountPassword(String value);

	boolean validateServiceDependencies(String value);

	boolean validateServiceDescription(String value);

	boolean validateServiceDisplayName(String value);

	boolean validateServiceName(String value);

	boolean validateServiceStatus(WindowsServiceStatusType value);

	boolean validateStartParams(String value);

	boolean validateStartupType(WindowsServiceStartupType value);
}
