/***************************************************************************************************
 * Copyright (c) 2003, 2007 IBM Corporation Licensed Material - Property of IBM. All rights
 * reserved.
 * 
 * US Government Users Restricted Rights - Use, duplication or disclosure v1.0 restricted by GSA ADP
 * Schedule Contract with IBM Corp.
 * 
 * Contributors: IBM Corporation - initial API and implementation
 **************************************************************************************************/
package com.ibm.ccl.soa.deploy.core.constraint.validation;

import org.eclipse.emf.common.util.EMap;
import org.eclipse.emf.ecore.util.FeatureMap;

import com.ibm.ccl.soa.deploy.core.constraint.AndConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.CollocationConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.DeferredHostingConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.EnumerationConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.EqualsConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.ExclusionConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.GroupCardinalityConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.MemberCardinalityConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.NotConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.OrConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.ProductIdentifierConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.RangeConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.SingleValue;
import com.ibm.ccl.soa.deploy.core.constraint.TypeConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.VersionConstraint;
import com.ibm.ccl.soa.deploy.core.constraint.XorConstraint;

/**
 * A sample validator interface for {@link com.ibm.ccl.soa.deploy.core.constraint.ConstraintRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstraintRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);

	boolean validateXMLNSPrefixMap(EMap value);

	boolean validateXSISchemaLocation(EMap value);

	boolean validateConstraintAnd(AndConstraint value);

	boolean validateConstraintCollocation(CollocationConstraint value);

	boolean validateConstraintDeferredHosting(DeferredHostingConstraint value);

	boolean validateConstraintEnumeration(EnumerationConstraint value);

	boolean validateConstraintEquals(EqualsConstraint value);

	boolean validateConstraintExclusion(ExclusionConstraint value);

	boolean validateConstraintGroupCardinality(GroupCardinalityConstraint value);

	boolean validateConstraintMemberCardinality(MemberCardinalityConstraint value);

	boolean validateConstraintNot(NotConstraint value);

	boolean validateConstraintOr(OrConstraint value);

	boolean validateConstraintProductIdentifier(ProductIdentifierConstraint value);

	boolean validateConstraintRange(RangeConstraint value);

	boolean validateConstraintType(TypeConstraint value);

	boolean validateConstraintVersion(VersionConstraint value);

	boolean validateConstraintXor(XorConstraint value);

	boolean validateValue(SingleValue value);
}
